prototypes/go/app/listener/listener.go
Using context with timeout for reading messages caused program to slow down heavily with increasing number of messages
**Before**
> {
"timestamp": "2019-11-08T15:45:01Z",
**"duration": 659.337115,**
"items": 1000,
"levelname": "info",
"message": "batch finished",
**"write/sec": 1.5166748196785493**
}
**After**
> {
"timestamp": "2019-11-08T15:27:16Z",
**"duration": 19.86282347,**
"items": 1000,
"levelname": "info",
"message": "batch finished",
**"write/sec": 50.34530974462716**
}
=> Use background context instead context with timeout

dev/scripts/metrics.sh, dev/scripts/systems_applicable.sh, manager/manager.go, manager/middlewares/prometheus.go, manager/middlewares/swagger.go
SPM-28
- added `patchman_engine` prefix to metric names
- unified parametrized endpoints counters
- Prometheus and Swagger setup moved to middlewares package
=> Set up Prometheus metrics

Dockerfile.centos, Dockerfile.rhel8, Dockerfile.test
The `go vendor` created directory was not used by the build, forcing double downloading of dependencies.
=> Improve build times by pre-downloading dependencies in module mode

base/models/models.go, database/schema/create_schema.sql, docs/openapi.json, manager/controllers/advisories.go, manager/controllers/advisory_detail.go, manager/controllers/systems.go, scripts/test_data.sql
- Rename all occurences of `errata` to `advisory`, to correspond with frontend and API nomenclature
- Change `advisory_type` names to correspond to the ones we receive from VMaaS
- Remove `s3_url` from hosts, since we don't download archives.
=> Database refactoring

base/base.go, base/models/models.go, conf/common.env, conf/listener.env, conf/vmaas_sync.env, listener/listener.go, manager/controllers/advisory_detail.go, openshift/deploy/database.yml, openshift/deploy/vmaas_sync.yml, scripts/test_data.sql, vmaas_sync/advisory_sync.go, vmaas_sync/advisory_sync_test.go, vmaas_sync/vmaas_sync.go
Implements syncing advisories from VMaaS. Contains just storing the data.
Next step will be forcing re-evaluation of systems, based on information of updated repos.
The synchronization can be caused by running `dev/scripts/platform_sync.sh` script in local development environmnet.
=> Sync advisories from VMaaS

base/database/batch.go, base/utils/gin.go, base/utils/rpm.go, database/schema/create_schema.sql, dev/scripts/platform_delete.sh, go.mod, listener/common_test.go, listener/delete.go, listener/delete_test.go, listener/event.go, listener/listener.go, listener/upload.go, listener/upload_test.go, platform/platform.go
- Removed 'deleted_systems' table is not needed, since we are querying
inventory for systems, and can detect out-of-order deletions that way.
This table was used as a guard against accidentally reordered upload,
and delete messages. If in a rare case, a delete message was processed
before an upload message for same host, it would mean that host would
be deleted and re-created. We can detect this when processing an upload
message. If the call to get 'system_profile' returns no data, host is deleted.
- Re-organized the handlers, to make event parsing code shared.
=> Implement host deletion

vmaas_sync/advisory_sync.go
An indexing error resulted in vmaas_sync container crashing after each sync.
=> Fix indexing error in advisory_sync

evaluator/evaluate.go, evaluator/evaluate_test.go, listener/upload.go, listener/upload_test.go, platform/vmaas.go
VMaaS call for `/v3/updates` was implemented, this PR changes evaluation behaviour to use this endpoint, and adds modules + repos to VMaaS request
=> Move to v3/updates call, add more info to vmaas request

base/database/setup.go, conf/common.env, conf/listener.env, conf/test.env, listener/listener.go, openshift/deploy/listener.yml, openshift/deploy/manager.yml, openshift/deploy/vmaas_sync.yml
Change the concurrency profile in listener
- We'll have 8 listeners
- Each listener will have 8 consumers,
- Scheduled on 8 hardware threads
This should allow us to process 64 messages at a time, and allow us to schedule goroutines on hardware threads, so the whole pipeline won't be blocked on waiting for database.
=> Concurrency

manager/controllers/advisories.go, manager/controllers/advisory_systems.go, manager/controllers/system_advisories.go, manager/controllers/systems.go
- Remove description, summary from sort fields
- Add type to sort keys for advisories
- Add `id` sort key to openapi doc
=> Make advisories sortable by type

openshift/deploy/listener.yml, openshift/deploy/manager.yml, openshift/deploy/vmaas_sync.yml
- Env variables must be string
- missed default consumer count from listener
=> Fix openshift templates

base/models/models.go, base/mqueue/mqueue_test.go, database/migrations/002_base_schema.up.sql, database/migrations/005_adv_severity.down.sql, database/migrations/005_adv_severity.up.sql, database/schema/create_schema.sql, database/schema_test.go, manager/controllers/advisories.go, manager/controllers/advisory_detail.go, manager/controllers/advisory_detail_test.go, manager/controllers/structures.go, manager/controllers/system_advisories.go, scripts/test_data.sql, vmaas_sync/advisory_sync.go
Sync advisory severity from vmaas.
- After internal discussion interprets `None` as null. Provides only index in the frontend, since strings will always be translated.
=> Advisory severity

manager/controllers/advisory_systems.go, manager/controllers/advisory_systems_test.go
Data provided in `/advisoies/:id/systems` was invalid.
=> Fix advisory counts per type in advisory/id/systems

database/migrations/004_cache_functions.up.sql, database/migrations/006_simplify_sql.up.sql, database/schema/clear_db.sql, database/schema/create_schema.sql, database/schema/init_schema.sh, database/schema_test.go
- Remove duplication between multiple `refresh_*` functions
- Simplify opt_out trigger
- Remove all tables and functions before testing migrations
=> Simplify stored procedures

database/migrations/008_fix_system_caches.down.sql, database/migrations/008_fix_system_caches.up.sql, database/schema/create_schema.sql
Fix `refresh_system_caches` always modyfying all `system_platform` rows.
=> Fix refresh_system_caches modifying all system_platforms

base/database/query.go, base/database/query_test.go, manager/controllers/advisories.go, manager/controllers/advisories_test.go, manager/controllers/advisory_systems.go, manager/controllers/filter.go, manager/controllers/filter_test.go, manager/controllers/structures.go, manager/controllers/system_advisories.go, manager/controllers/systems.go, manager/controllers/utils.go
Reworks the filter & sort implementation, so that SQL column definitions are stored along with structs which will be retrieved from database
Also avoids loading whole models. Instead loads just structs which will be returned from the API.
=> Use custom tag to denote struct queries

platform/Dockerfile
Old link is redirecting & blocking test runs.
=> Fix kafka download link

base/mqueue/mqueue.go
The issues in QA environment were probably caused by loading too many messages.
+ 8 consumers  = 8 x 10MB = 80MB in raw buffers
+ deserialized = 2 x 80MB = 160MB in just the data size.
With GOGC being 100 by default, go will allocate 100% of previous memory snapshot before forcing a GC. which will result in 320 MB peak ram. 
320MB + our base memory experienced by listener with no load = 320MB + 30MB = 350MB, just what we experienced.
With max buffer of 1MB per listener:
8 x 1MB = 8MB ...  max buffers
2x 8MB = 16MB ... buffers + deserialized
2x 16MB = 32MB .... Peak before GC
32MB + 30 MB = 80MB , we should be under 128 MB resource limit.
=> Change max buffer size for kafka consumer

database/migrations/007_system_culling.up.sql, database/migrations/009_aad_counts.up.sql, database/schema/create_schema.sql
Attempts to fix issue when system_update trigger left rows with affected_systems of 0 in the table.
Most probable cause for this issue was the fact that queries within CTE are not evaluated sequentially, and subsequent queries do not see changes of previous queries on underlying tables.
This meant that changes performed by UPDATE (decrement) were not seen by DELETE, resulting in missed deletes.
New approach uses `to_update_advisories` temporary table with row locks as a source of truth, and performs updates, inserts, deletes based on information stored in it.
=> Re-work the system_update trigger to fix skipped DELETEs

base/mqueue/event.go, base/mqueue/mqueue.go, base/mqueue/mqueue_test.go, base/mqueue/testing.go, conf/evaluator_common.env, conf/listener.env, conf/test.env, evaluator/evaluate.go, listener/common_test.go, listener/delete.go, listener/delete_test.go, listener/listener.go, listener/metrics.go, listener/upload.go, listener/upload_test.go, platform/entrypoint.sh, platform/inventory.go, platform/platform.go, vmaas_sync/send_messages.go, vmaas_sync/vmaas_sync_test.go
Allows us to not call inventory at all, we can get all the info we need from kafka messages.
- Changes `mqueue.go` to only deal with kafka messages
- `events.go` now deals with standard event format for delete and eval messages.
- `upload.go` Parses messages into custom event format
- Platform mock code now uses `map[string]interface{}` instead of string interpolation
Tied with https://github.com/RedHatInsights/e2e-deploy/pull/1124
=> Move to host-egress queue

manager/middlewares/rbac.go
Since the `patch` RBAC role is now available on CI, we can re-enable the RBAC checking at least for CI.
=> Re-enable RBAC check

manager/controllers/filter.go, manager/controllers/filter_test.go, manager/controllers/utils.go
Current code which handles filters as an array has an error, which results in default filters always being applied.
This PR changes this behavior, and always handles filters as a map keyed by field name to which a filter is applied.
=> Always handle filters as a map

database/migrations/011_culling_timestamps.down.sql, database/migrations/011_culling_timestamps.up.sql, database/schema/create_schema.sql
We've used the wrong timestamp for marking systems stale.
=> Fix wrong timestamp for system culling

base/models/models.go, base/utils/core.go, conf/test.env, conf/vmaas_sync.env, dev/test_data.sql, platform/vmaas.go, vmaas_sync/advisory_sync.go, vmaas_sync/repo_based.go, vmaas_sync/repo_based_test.go, vmaas_sync/send_messages.go, vmaas_sync/vmaas_sync.go, vmaas_sync/vmaas_sync_test.go
- Implemented repo-based recalculation in vmaas_sync.
- Added `ENABLE_REPO_BASED_RE_EVALUATION` env variable.
- It's needed to be in vmaas_sync OpenShift config before merging.
=> Added repo-based re-evaluation - vmaas_sync

base/models/models.go, listener/common_test.go, listener/metrics.go, listener/upload.go, listener/upload_test.go
- Wrap code in single transaction, previously it would run in 2 transactions
- Skip sending eval messages for systems, which haven't had their `system_profile` changed.
- Skip re-writing `vmaas_json` if it haven't changed
=> Optimize listener message handling

database/migrations/014_table_config.up.sql, database/schema/create_schema.sql, evaluator/evaluate.go, listener/upload.go
Should allow us to get less dead tuples due to [HOT](https://malisper.me/postgres-heap-only-tuples/) updates & more aggressive autovacuuming.
Will consume more disk space, but should significantly reduce performance degradation on insert heavy tables.
After the migration is applied, `VACUUM FULL` on the tables will need to be performed, and it can't be run from within the migrations.
=> Change table fillfactor

base/database/query.go, base/database/query_test.go, manager/controllers/filter.go, manager/controllers/filter_test.go, manager/controllers/utils.go
We used to rely on raw string values being accepted by postgresql as query parameters.
This PR implements parsing values in filter query parameters so we catch and properly report invalid values.
=> Parse filter values

manager/middlewares/rbac.go
- read `ENABLE_RBAC` env var only once
=> Simplified RBAC() middleware implementation

base/database/testing.go, database_admin/migrations/015_fix_caches.up.sql, database_admin/schema/create_schema.sql, evaluator/evaluate.go, evaluator/evaluate_test.go, listener/common_test.go, listener/upload.go, vmaas_sync/system_culling.go
There were several issues which caused invalid caches.
- Not locking `advisory_account_data` in between 2 updates when evaluation could result in an inconsistencies when evaluating 2 package profiles with same advisories from same account
- Not locking `system_platform` rows when performing system culling tasks
- Not locking `system_platform` when inserting from listener
=> Fix cache calculation

dev/test_data.sql, vmaas_sync/repo_based.go, vmaas_sync/repo_based_test.go
- Fixed repo-base inventory IDs selecting, use `DISTINCT`
=> Repo based fix

base/database/database.go, base/database/testing.go, evaluator/evaluate.go, evaluator/evaluate_test.go, manager/controllers/advisories.go
- Revert back to incremental calculation
- Sequence of actions is now based on tables, first locking `system_platform`, then updating `system_advisories`, and then updating `advisory_account_data`, instead of interleaving updating 
`system_advisories` and `advisory_account_data` for unpatched and patched advisories
- Fixes to system_culling in previous PR should fix some causes of cache inconsistencies
=> Fix caches, attempt #4

evaluator/evaluate.go, evaluator/evaluate_test.go
- Does not use database function for calculating system caches
- Updates last_evaluation when updating caches, removing one write per evaluation
=> Calculate system caches in code

evaluator/evaluate.go, listener/upload.go
Listener crashing when yum repos are empty strings
Evaluator crashing on nonexistant advisories
=> Fix master issues

base/database/testing.go, database_admin/migrations/019_caches_fix_v2.up.sql, database_admin/schema/create_schema.sql, listener/upload.go, vmaas_sync/system_culling_test.go
The `on_system_timestamp_update` did not call the trigger to update cached counts after updating the `stale` flag.
This changes so that listener updates this flag manually.
=> Manual updating of stale flag in listener

base/mqueue/mqueue.go, base/utils/awscloudwatch.go, base/utils/core.go, base/utils/core_test.go, base/utils/identity_test.go, base/utils/rpm_test.go, go.mod, go.sum, listener/listener_test.go, main.go, vmaas_sync/metrics.go, vmaas_sync/system_culling.go
This should allow us to see fatal errors in external logging such as cloudwatch.
This is only a temporary solution, since panics happening in other goroutines will still just tear down the whole process.
=> Handle panics + log errors explicitly

listener/delete.go, listener/upload.go
Should provide us more information in the per-attempt log when  delete or eval handler fails.
=> Add missing error wrapping

Jenkinsfile-smoke.groovy
Jenkins job for running smoke tests is looking for a job config in project repos, therefore adding one.
=> add Jenkins file for smoke tests

base/utils/rpm.go, evaluator/evaluate.go
- Old implementation still assumed one entry per package name.
- There was a bug in formatting NEVRAs
=> Fix multiple installed packages handling

evaluator/evaluate.go, vmaas_sync/advisory_sync.go, vmaas_sync/repo_based.go, vmaas_sync/vmaas_sync.go
By repeatedly slicing the packages array. Should only happen when we have too many packages in a page of advisories
=> Make package downloads size limited

docs/openapi.json, manager/controllers/packages.go, manager/controllers/packages_test.go, manager/controllers/system_packages.go, manager/controllers/system_packages_test.go
First implementation of per-account package data, currently calculating everything dynamically. If performance will be a problem, we'll move to pre-calculated table.
=> [WIP] Basic dynamic implementation of packages endpoint

vmaas_sync/send_messages.go
Last recalc we spent 15 minutes just logging all of the systems and sending messages
=> Don't log system ids in vmaas sync

database_admin/migrations/039_system_package_updatable.up.sql, database_admin/schema/create_schema.sql, manager/controllers/packages.go
We currently require a `system_package_<part>`  table scan for packages endpoint. This adds computed column, which is then included in the index, and is used for the counts. This should remove the need to do full table scan on the partition, and remove the worst offender in the slowness of packages endpoint.
=> Remove the need for the packages endpoint to visit whole partition

manager/controllers/advisories_test.go, manager/controllers/advisory_systems_test.go, manager/controllers/package_systems.go, manager/controllers/package_systems_test.go, manager/controllers/packages.go, manager/controllers/packages_test.go, manager/controllers/system_advisories_test.go, manager/controllers/system_packages.go, manager/controllers/system_packages_test.go, manager/controllers/systems_test.go
- don't return 500 (server error) but 400 (bad request) when too big `offset` param set for manager's listing endpoints
=> Fixed invalid offset handling

database/init.sh, database_admin/config.sql
log_min_duration_statement can only be set by superuser, we can either grant db_admin superuser privileges, or set this in DB creation, when user is postgres
=> fix(database): Fix ERROR message

base/metrics/metrics.go, manager/manager.go, scripts/generate_docs.sh
engine version is shown in metrics as
```
patchman_engine_core_info{version="v1.4.2"} 1
```
=> Indicate engine version in docs and API

manager/controllers/systems_test.go, manager/controllers/utils.go
Allow tags without the value portion.
Tags query parameter now accepts 2 formats:
`tags=ns/k=v` and `tags=ns/k`
=> Support tags without value

vmaas_sync/metrics_cyndi.go
it runs every 15s and does fullscan over inventory.hosts
this change reduces cost from
```
Aggregate  (cost=415838.35..415838.36 rows=1 width=8)
->  Unique  (cost=405794.02..408663.83 rows=573962 width=32)
->  Sort  (cost=405794.02..407228.92 rows=573962 width=32)
Sort Key: (jsonb_array_elements(hosts_v1_1607594495056200400.tags))
->  Gather  (cost=1000.00..337158.84 rows=573962 width=32)
Workers Planned: 2
->  ProjectSet  (cost=0.00..278762.64 rows=23915100 width=32)
->  Parallel Seq Scan on hosts_v1_1607594495056200400  (cost=0.00..157393.51 rows=239151 width=319)
```
to
```
Aggregate  (cost=221569.25..221569.26 rows=1 width=8)
->  Gather  (cost=1000.00..219177.74 rows=191321 width=32)
Workers Planned: 2
->  ProjectSet  (cost=0.00..199045.64 rows=7971700 width=32)
->  Parallel Seq Scan …
```
=> improve cyndi tag metrics query

.golangci.yml
Resolve warnings printed by `golangci-lint run`:
~~~
WARN [runner] The linter 'interfacer' is deprecated due to: The repository of the linter has been archived by the owner. 
WARN [runner] The linter 'maligned' is deprecated due to: The repository of the linter has been archived by the owner. Use govet 'fieldalignment' instead.
~~~
=> updated golangci-lint config

scripts/feed_db.sh, scripts/go_test_db.sh, scripts/wait-for-services.sh
wait for full db schema when running tests and dirty=f
allow components running on schema dirty=t
=> SPM-812 fix wait-for-services criteria

manager/middlewares/authentication.go
Failure to find an account is not an authentication failure. The account could be valid. Fixes SPM-815
=> Use no content response when account is not found

manager/controllers/utils.go
Nulls should be conceptually smaller than actual values. The opposite is default in PostgreSQL.
=> Sorting: make nulls sort as smaller than actual values

base/database/utils.go
We don't store advisory_id in package info in new approach - syncing from vmaas/pkgtree. Anyway this info (package - advisory relation) was not shown anywhere.
=> SPM-853 Fix package detail request with empty advisory_id

base/base.go, base/base_test.go, listener/events.go, listener/upload_test.go, vmaas_sync/advisory_sync.go, vmaas_sync/advisory_sync_test.go, vmaas_sync/system_culling_test.go
We should accept datetime formats with optional fields. Go doesn't like what the platform is sending us, so let's add multiple formats for parsing. 
Also added logging and reporting error that occur when parsing messages.
=> Fix message processing, add more lenient datetime parser

docker-compose.yml
improved speed of podman-compose up --build
speeds up podman-compose build from 30s to 5s
=> SPM-910: build image just once

base/database/testing.go, evaluator/evaluate.go, evaluator/evaluate_packages.go, evaluator/evaluate_test.go
If we don't use intermediate updates anywhere, why store them ?
=> SPM-937: Add support for pruning updates (storing only latest)

pr_check.sh
vmaas-reposcan gets OOMKilled during sync if it does not have enough resources, default resource limit in ephemeral is 256Mb which is not enough, so we need to respect settings from vmaas clowdapp.yaml
=> SPM-674 respect vmaas resource settings in ephemeral

base/database/utils.go, manager/controllers/packages.go
mostly by removing redundant joins to system_platform and package_name
original query
Limit  (cost=609870.56..609870.61 rows=20 width=72) (actual time=3644.560..3648.030 rows=20 loops=1)
improved query
Limit  (cost=105721.03..105721.08 rows=20 width=72)
=> SPM-1055: improve /packages query

database_admin/migrations/074_stale_edge_systems.down.sql, database_admin/migrations/074_stale_edge_systems.up.sql, database_admin/schema/create_schema.sql
- the same approach used for SPM-626
- then it will be deleted automatically using system culling job (vmaas-sync)
=> SPM-1331: Mark db systems with host_type=edge as stale (db migr.)

Dockerfile
seems to be fixed either in the latest ubi:8.6 or by removal of psql libraries in a08bf276a0df2e862b1ddbbc72da368377504672
=> SPM-1536: update to ubi:8.6

evaluator/evaluate.go
It should not really happen in stage/prod but it is possible to create such db record since vmaas_json is text type without not null constraint. 
Skip the system eval recalc when `VmaasJSON` field (string) is `"" `
=> SPM-1574: don't panic when vmaas_json is null in db

base/mqueue/event.go, deploy/clowdapp.yaml, listener/upload.go
**NOTE**: we need to be careful when changing `BatchSize`. I experienced some OOMKilled errors in ephemeral. Probably due to usage of 8 consumers (default in clowdapp.yaml) in evaluator-recalc. 
=> SPM-1447: Make BatchSize configurable

vmaas_sync/vmaas_sync.go, vmaas_sync/vmaas_sync_test.go
fixing 
```
time="2022-06-20T10:27:03Z" level=error msg="Failed to retrieve VMaaS websocket message" err="websocket: close 1005 (no status)"
time="2022-06-20T10:27:03Z" level=error msg="Websocket error occurred, waiting" err="websocket: close 1005 (no status)"
```
vmaas closes websocket connection if subscribed client won't respond to `ping` message in predetermined timeout. Patch is not responding because it's syncing data which blocks websocket client.
=> SPM-1580: don't block websocket client with msg handler

base/database/testing.go, base/models/models.go, base/notification/notification.go, database_admin/migrations/082_advisory_notified_column.down.sql, database_admin/migrations/082_advisory_notified_column.up.sql, database_admin/schema/create_schema.sql, evaluator/evaluate.go, evaluator/notifications.go, evaluator/notifications_test.go
After these changes we would notify each new advisory only once per account because it is too verbose to do it for every system.
=> SPM-1484: Notify new advisory only once per account

listener/upload.go
We don;t need to send 2 messages - `received` and `error` when the message will not be evaluated (e.g. coming from yupana). Instead we will send only `received` msg with `StatusMsg` explaining the message was skipped.
=> Send only 1 payload status for skipped messages

manager/controllers/advisories.go, manager/controllers/advisories_test.go, manager/controllers/advisory_systems.go, manager/controllers/baseline_systems.go, manager/controllers/baseline_systems_test.go, manager/controllers/baselines.go, manager/controllers/baselines_test.go, manager/controllers/package_systems.go, manager/controllers/package_versions.go, manager/controllers/packages.go, manager/controllers/system_advisories.go, manager/controllers/system_packages.go, manager/controllers/systems.go, manager/controllers/systems_test.go, manager/controllers/utils.go
Some links in response metadata were like `/api/patch/v1/advisories`, others were just `/packages`. Either way, they were hardcoded and didn't show the correct path for v2 api. Use `gin.Context.FullPath` to get the correct path for links
=> SPM-1622: fix api links

database_admin/entrypoint.sh, database_admin/migrate.go, database_admin/update.go, deploy/clowdapp.yaml
Initially I wanted to use k8s job which runs migrations and add initContainer to all deployements to wait till migration is ready. However, using plain job suffers from clowder usage - it doesn't have the correct config and can't pull the image and ClowdJob triggered by ClowdJobInvoction can't be run if the app is not running so it can't be used for migrations.
The implementation is basically the same as in Vulnerability
1. manager pod has initContainer which runs migrations
2. to avoid concurrency we are using pg_advisory_lock
3. if the migration is not successful, init container panics which _should_ result in failure and new manager won't be deployed
4. other pods (evaluators, listeners,...) will start immediately and they may be in CrashLoop state until migrations are not successful …
=> use initContainer for db migration

manager/controllers/baseline_create.go, manager/controllers/baseline_create_test.go, manager/controllers/baseline_update.go, manager/controllers/baseline_update_test.go
This rewords the duplicate baseline name error message from 'baseline name already exists' to 'patch template name already exists'. 
=> reword duplicate baseline name error message

manager/controllers/system_packages.go
Basically the same thing as for https://github.com/RedHatInsights/patchman-engine/pull/1026, there is `""` vs null issue in DB, so we might want to use left join
with `JOIN`
```
-d "{\"query\": \"select pn.name from system_package sp JOIN package p ON sp.package_id = p.id JOIN strings sum ON p.summary_hash = sum.id JOIN package_name pn ON pn.id = sp.name_id where sp.system_id = '1422060' and sp.name_id = '660016426'\"}" -s | jq
{
"result": [
[
"name"
]
],
"error": ""
}
```
with LEFT JOIN
```
-d "{\"query\": \"select pn.name from system_package sp JOIN package p ON sp.package_id = p.id LEFT JOIN strings sum ON p.summary_hash = sum.id JOIN package_name pn ON pn.id = sp.name_id where sp.system_id = '1422060' and sp.name_id = '660016426'\"}" -s | jq
{
"result": [
[
"name"
],
[
"thirdparty"
] …
```
=> SPM-1326: fix missing thirdparty package in system/packages

base/utils/gin.go
```
base/utils/gin.go:59:9: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
srv := http.Server{Addr: addr, Handler: handler}
```
I've set same value as is default in nginx
=> Add ReadHeaderTimeout

deploy/clowdapp.yaml
there is a problem when there is a problem with job and job keeps running. Then it blocks newer jobs due to forbid concurrency policy 
=> set timeout for jobs

manager/middlewares/logger.go, manager/middlewares/prometheus.go
Example:
```
patchman_engine_manager_request_durations_bucket{endpoint="GET/api/patch/v2/advisories/",le="1"} 10
patchman_engine_manager_request_durations_bucket{endpoint="GET/api/patch/v2/advisories/",le="1.5"} 10
patchman_engine_manager_request_durations_bucket{endpoint="GET/api/patch/v2/advisories/",le="1.75"} 10
patchman_engine_manager_request_durations_bucket{endpoint="GET/api/patch/v2/advisories/",le="2"} 10
patchman_engine_manager_request_durations_bucket{endpoint="GET/api/patch/v2/advisories/",le="2.5"} 10
patchman_engine_manager_request_durations_bucket{endpoint="GET/api/patch/v2/advisories/",le="3"} 10
patchman_engine_manager_request_durations_bucket{endpoint="GET/api/patch/v2/advisories/",le="3.5"} 10
patchman_engine_manager_request_durations_bucket{endpoint="GET/api/patch/v2/ad …
```
=> SPM-1564 add metrics for request durations per API endpoint

manager/controllers/advisories.go, manager/controllers/advisory_systems.go, manager/controllers/baseline_systems.go, manager/controllers/baselines.go, manager/controllers/package_systems.go, manager/controllers/package_versions.go, manager/controllers/packages.go, manager/controllers/system_advisories.go, manager/controllers/system_packages.go, manager/controllers/systems.go, manager/controllers/utils.go
make sort stable by using secondary sort key (most of the time `id`)
=> SPM-1426: add secondary sort key

tasks/caches/refresh_advisory_caches.go, tasks/caches/refresh_advisory_caches_test.go
~~improvements:~~
~~- set max number of goroutines for refresh job, currently it runs as many as possible goroutines (for 80k accounts in prod) which results in locking all rows for accounts at the same moment~~
~~- query accounts which has inconsistencies in system counts and only refresh these accounts~~
~~the problem can be in the query which finds accounts, it works quite fast in stage but it timeouts in gabi in prod and it has quite high cost~~
~~Subquery Scan on sums  (cost=3722126.53..3723369.97 rows=199 width=4)"~~
~~any ideas how to improve it further?~~
After discussion with @MichaelMraka we've decided to refresh all caches at once by not supplying any account ids
```
refresh_advisory_caches(NULL, NULL)
```
=> SPM-1721: optimize advisory cache refresh

.github/workflows/semantic-release.yml, Dockerfile, deploy/clowdapp.yaml, docker-compose.prod.yml, docker-compose.yml, docs/admin/openapi.json, docs/docs.go, main.go, manager/manager.go, manager/middlewares/swagger.go, manager/routes/routes.go, scripts/check-dockercomposes.sh, scripts/generate_docs.sh, turnpike/admin_api.go, turnpike/controllers/admin.go
- move admin api to its own pod
- generate openapi for admin api
- api is exposed on `/api/patch/admin`
- openapi UI is on `/api/patch/admin/openapi/index.html` on `PublicPort` or `8085` if ran locally
=> SPM-1661: rework turnpike/admin api

base/api/client.go, docs/admin/openapi.json, listener/common_test.go, listener/upload.go, listener/upload_test.go, platform/platform.go
- primarily read yum_updates from yum_updates_s3_url
- if that does not exist read it from old yum_updates
- added `/yum_updates` endpoint to platform mock for tests
- added more generic logs to client
I haven't added retrying if yum_updates_s3_url is unavailable, should I?
TODO:
=> SPM-1735: read yum_updates from s3

docs/v2/openapi.json, manager/controllers/systems.go, manager/controllers/systemtags.go, manager/controllers/systemtags_test.go, manager/controllers/utils.go, manager/routes/routes.go
Introduces `/tags` which returns tags with host counts effective for this service.
Along the way it refactors following:
* moves `SystemTag` type
* use of common `ih` alias for `inventory.hosts` table within tags filter
* filter tags where clause split
=> SPM-1737: introduce tags REST API

dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
it's caused by pushing metrics through push-proxy and there are 3 proxies
=> SPM-1712: fix tripled metrics counts

deploy/clowdapp.yaml
try to run package refresh job in 1 golang thread to see if it is not causing any issues
=> SPM-1807: run package refresh in 1 thread

manager/manager.go
we need to return 500 when app panics, currently, the app will not respond to api call in case of panic
=> return 500 when app panics

listener/upload.go, platform/platform.go
Rohini confirmed it should be `s3url` not `s3_url`
=> fix s3 url field name

manager/controllers/utils.go
example of another query which caused 500 on tags filter
```sh
tags=%27insights-client%2Fdemo%3D%22%7B%7Bslug%7D%7D%22%27
```
=> SPM-1921: fix tags 500 by trimming quotes

database_admin/migrations/106_alphanumeric_collation.down.sql, database_admin/migrations/106_alphanumeric_collation.up.sql, database_admin/schema/create_schema.sql, manager/controllers/common_attributes.go, manager/controllers/systems_test.go, manager/controllers/utils.go
- use collation to use natural sort for alphanumerical strings (OS) - see commit message
- make nulls last when sorting, based on SPM-1831 it is the common way of sorting by all apps
=> SPM-1955, SPM-1831 - fix sorting

manager/routes/routes.go
all apis with trailing slash should be redirected to an api without trailing slash
e.g. `/systems/?page=1` should be redirected to `/systems?page=1`
but all apis without trailing slash should not be redirected
e.g. `/systems?page=1` should not be redirected to `/systems/?page=1`
=> SPM-1982: handlers on api.group should not have trailing /

base/database/testing.go, database_admin/migrations/107_applicable_advisories.down.sql, database_admin/migrations/107_applicable_advisories.up.sql, database_admin/schema/create_schema.sql, evaluator/evaluate.go, evaluator/evaluate_advisories.go, manager/controllers/advisories.go, manager/controllers/advisories_export_test.go, manager/controllers/advisories_test.go
- applicable advisory is any advisory which can be applied to a system
- installable advisory is an applicable advisory which can be installed on a system based on the current template `to_date` 
=> SPM-1986: installable should be subset of applicable

evaluator/evaluate_test.go, evaluator/package_cache.go, evaluator/vmaas_cache.go, go.mod, go.sum, manager/controllers/advisory_detail.go
- checksum is assigned to a new variable after every upload, so it has a different pointer and there is no cache hit
=> SPM-1990: use checksum value as vmaas-cache key

base/core/gintesting.go, manager/controllers/advisories.go, manager/controllers/advisories_test.go, manager/controllers/system_advisories_export.go, manager/controllers/utils.go
- rename `applicable` systems filter to `installable` because DB uses `installable` column for showing results
- add default filter so won't show all applicable systems on v2 api
=> SPM-1984: fix v2/advisories backward compatibility

deploy/clowdapp.yaml, tasks/caches/caches.go, tasks/caches/refresh_advisory_caches.go, tasks/caches/refresh_advisory_caches_test.go
- run refresh for single account at a time
- run in 4 goroutines so we don't need to wait for refresh of bigger accounts
- add `SKIP_N_ACCOUNTS_REFRESH` to skip accounts refresh if something goes wrong and we want to continue with refresh
previous solution didn't finish in prod even after 6 hours with evaluator, listener, and all other jobs disabled
this finished in 9 minutes with evaluator, listener and jobs disabled
it is already pushed to prod using hotfix branch
=> SPM-2013: run advisory_refresh for individual accounts in 4 goroutines

base/inventory/inventory.go, listener/upload.go
Utilize relelasever from a system profile if RHSM version isn't set. This should improve reporting from RHUI systems.
SPM-2137
=> fix(listener): use releasever in vmaas_req

dev/test_data.sql, docs/admin/openapi.json, docs/v3/openapi.json, manager/controllers/package_systems.go, manager/controllers/package_systems_export_test.go, manager/controllers/package_systems_test.go, manager/controllers/packages_export_test.go, manager/controllers/packages_test.go, manager/controllers/systems_auth_test.go, manager/controllers/systems_ids_test.go, manager/controllers/systems_test.go, tasks/system_culling/system_culling_test.go, tasks/vmaas_sync/metrics_test.go
=> SPM-2135: add baseline_id and osversion into /package/systems

deploy/clowdapp.yaml
also change job schedule, some jobs take more than 1 hour which results in the next job to be scheduled just after the first on finishes. It causes jobs to start after 22:00 and interfere with upload evaluation
=> RHINENG-1162: add missing read replica envs for package refresh job

base/utils/rpm.go, evaluator/evaluate_packages.go, evaluator/package_cache.go
=> SPM-2119: remove package parsing where not needed

manager/controllers/advisories.go, manager/controllers/advisories_export.go, manager/controllers/advisories_test.go, manager/controllers/advisory_systems.go, manager/controllers/advisory_systems_export.go, manager/controllers/advisory_systems_test.go, manager/controllers/baseline_systems.go, manager/controllers/baselines.go, manager/controllers/filter.go, manager/controllers/filter_test.go, manager/controllers/package_systems.go, manager/controllers/package_systems_export.go, manager/controllers/package_systems_test.go, manager/controllers/package_versions.go, manager/controllers/packages.go, manager/controllers/packages_export.go, manager/controllers/packages_test.go, manager/controllers/system_advisories.go, manager/controllers/system_packages.go, manager/controllers/systems.go, manager/controllers/systems_export.go, manager/controllers/systems_test.go, manager/controllers/systemtags.go, manager/controllers/utils.go, manager/controllers/utils_test.go
=> RHINENG-1197: fix meta links 

base/database/utils.go, dev/test_data.sql, evaluator/package_cache_test.go, manager/controllers/package_systems.go, manager/controllers/package_systems_export_test.go, manager/controllers/package_systems_test.go, tasks/vmaas_sync/metrics_test.go
TODO:
original query - `(cost=1.40..26.06 rows=1 width=292) (actual time=2.213..3.124 rows=145 loops=1)`
```sql
SELECT
count(*) over () as total,
ih.tags as tags_str,
ih.groups as groups_str,
sp.inventory_id as id,
sp.display_name as display_name,
p.evra as installed_evra,
spkg.latest_evra as available_evra,
(update_status(spkg.update_data) = 'Installable') as updatable,
null as Tags,
bl.name as baseline_name,
sp.baseline_uptodate as baseline_uptodate,
bl.id as baseline_id,
ih.system_profile -> 'operating_system' ->> 'name' || ' ' || coalesce(
ih.system_profile -> 'operating_system' ->> 'major' || '.' || (ih.system_profile -> 'operating_system' ->> 'minor'),
''
) as os,
ih.system_profile -> 'rhsm' ->> 'version' as rhsm,
update_status(spkg.update_data) as update_status,
Groups as Groups …
```
=> POC: package systems

base/database/utils.go, manager/controllers/packages.go
original query `(cost=21664.34..21672.64 rows=200 width=66) (actual time=177.243..181.107 rows=300 loops=1)`
```sql
SELECT
count(*) over () as total,
pn.name as name,
pn.summary as summary,
res.systems_installed as systems_installed,
res.systems_installable as systems_updatable,
res.systems_installable as systems_installable,
res.systems_applicable as systems_applicable
FROM
package_name pn
JOIN (
SELECT
spkg.name_id as name_id,
count(*) as systems_installed,
count(*) filter (
where
update_status(spkg.update_data) = 'Installable'
) as systems_installable,
count(*) filter (
where
update_status(spkg.update_data) != 'None'
) as systems_applicable
FROM
system_package spkg
WHERE
spkg.rh_account_id = 37
AND spkg.system_id IN (
SELECT
sp.id
FROM
system_platform sp
JOIN inventory.hosts ih ON …
```
=> POC: use system_package2 in /packages

Dockerfile, scripts/go_test.sh, scripts/go_test_db.sh
=> RHINENG-1715: use gotestsum to collect test summary

listener/upload.go
insert/update should be handled by the `storeOrUpdateSysPlatform` function which should avoid doing upserts
=> RHINENG-1604: remove duplicated insert/update to system_platform

database_admin/migrations/116_delete_system_package2.down.sql, database_admin/migrations/116_delete_system_package2.up.sql, database_admin/schema/create_schema.sql
error when deleting system in listener
```
time="2023-09-12T10:14:30Z" level=error msg="Try failed" attempt=3 err="Could not opt_out system: ERROR: update or delete on table \"system_platform_8\" violates foreign key constraint \"system_package2_rh_account_id_system_id_fkey9\" on table \"system_package2\" (SQLSTATE 23503)"
time="2023-09-12T10:14:31Z" level=error msg="Could not delete system" err="ERROR: update or delete on table \"system_platform_8\" violates foreign key constraint \"system_package2_rh_account_id_system_id_fkey9\" on table \"system_package2\" (SQLSTATE 23503)" inventoryID=803eea15-79a5-4b9f-863b-631409911ed0
```
=> POC: delete system also from system_package2

deploy/clowdapp.yaml, docker-compose.prod.yml, docker-compose.yml, main.go, scripts/check-dockercomposes.sh, tasks/migration/migrate_system_package_data.go
=> POC: add job to migrate data from system_package

base/mqueue/mqueue_impl_gokafka.go, base/utils/config.go, deploy/clowdapp.yaml
=> RHINENG-2394: allow Kafka TLS without CA cert

evaluator/evaluate_advisories.go, evaluator/evaluate_advisories_test.go, evaluator/evaluate_test.go, evaluator/notifications_test.go, tasks/cleaning/clean_unused_data_test.go
=> RHINENG-2867: lazy insert missing errata

base/vmaas/vmaas.go, platform/vmaas.go, tasks/vmaas_sync/repo_based.go, tasks/vmaas_sync/repo_based_test.go, tasks/vmaas_sync/repo_sync.go, tasks/vmaas_sync/vmaas_sync_test.go
=> RHINENG-2610: use latest_repo_change timestamp for repo based re-eval

docs/v3/openapi.json, manager/controllers/systems_advisories_view.go, manager/controllers/systems_advisories_view_test.go
=>  RHINENG-2420: support filtering in /view{/systems/advisories,/advisories/systems}

base/mqueue/mqueue_impl_gokafka.go, base/utils/config.go, conf/cdappconfig.json, go.mod, go.sum
- we need to use multiple kafka brokers - use KafkaServers for that
- we probably no longer need to overwrite KAFKA_ADDRESS, it doesn't seem to be used anywhere
- handle Endpoint and PrivateEndpoint separately, structs are no longer equivalent after latest changes in Clowder (Enfpoint has extra ApiPath field and we can't convert PrivateEndpoint to Endpoint 😞 )
=> RHINENG-3742: Multiple kafka brokers

.golangci.yml, Dockerfile, base/utils/http.go, database_admin/schema/clear_db.sql, evaluator/evaluate_test.go, listener/common_test.go, listener/events_test.go, listener/upload_test.go, manager/controllers/advisories_test.go, manager/controllers/advisory_systems_v3.go, manager/controllers/baseline_delete.go, manager/controllers/baseline_detail.go, manager/controllers/baseline_update.go, manager/controllers/package_systems.go, manager/controllers/utils.go, tasks/vmaas_sync/advisory_sync_test.go
=> fix failing golanci-lint

deploy/clowdapp.yaml
if the job is not enabled, clowder won't create job resource and we cannot run it
reconciliation does not seem to be picking up disabled parameter, so it never creates the job 
=> POC: enable migration job

database_admin/migrations/119_migrate_system_package2.up.sql, database_admin/schema/create_schema.sql, turnpike/controllers/admin.go
=> RHINENG-5394: migrate system_package per account

turnpike/controllers/admin.go
=> RHINENG-5394: run vacuum in goroutine so api won't time out

database_admin/migrations/120_add_new_yupana_reporters.up.sql, database_admin/schema/create_schema.sql, deploy/clowdapp.yaml, listener/listener_test.go
I copied cyndi additionalFilters from Vulnerability since we didn't have it clowdapp.yaml. Do we have it defined somewhere else?
=> RHINENG-6036: exclude satellite and discovery reporters

database_admin/migrations/122_remove_system_package.down.sql, database_admin/migrations/122_remove_system_package.up.sql, database_admin/schema/create_schema.sql, dev/test_data.sql, manager/routes/routes.go, tasks/vmaas_sync/metrics_db_test.go, turnpike/controllers/admin.go
=> RHINENG-6031: drop old system_package table (POC cleanup)

manager/controllers/advisories_export_test.go, manager/controllers/advisories_test.go, manager/controllers/advisory_detail_test.go, manager/controllers/advisory_systems_export_test.go, manager/controllers/advisory_systems_test.go, manager/controllers/baseline_create_test.go, manager/controllers/baseline_delete_test.go, manager/controllers/baseline_detail_test.go, manager/controllers/baseline_systems_export_test.go, manager/controllers/baseline_systems_remove_test.go, manager/controllers/baseline_systems_test.go, manager/controllers/baseline_update_test.go, manager/controllers/common_test.go, manager/controllers/package_detail_test.go, manager/controllers/package_systems_export_test.go, manager/controllers/package_systems_test.go, manager/controllers/package_versions_test.go, manager/controllers/packages_export_test.go, manager/controllers/packages_test.go, manager/controllers/system_advisories_export_test.go, manager/controllers/system_advisories_test.go, manager/controllers/system_delete_test.go, manager/controllers/system_detail_test.go, manager/controllers/system_packages_export_test.go, manager/controllers/system_packages_test.go, manager/controllers/systems_advisories_view_test.go, manager/controllers/systems_auth_test.go, manager/controllers/systems_ids_test.go, manager/controllers/systems_test.go, manager/controllers/systemtags_test.go
- unify `method` and `routerMethod`
- use `routerPath`, `param`, and `queryString` to crete url
- update all function calls
- update doTestWrongOffset to work with the new CreateRequestRouterWithParams func
=> RHINENG-8049: improve CreateRequestRouterWithParams func

base/database/testing.go
There are 2 occurrences of the issue.
- first solved with adding EXISTS in `.Where()`
- second solved with removing `.Joins()`
=> RHINENG-8068: fix Join().Update() usage in the code

base/deprecations/base.go, base/deprecations/deprecations.go, manager/routes/routes.go
Also added ignore for `apiDeprecation` unused error, it may be used in the future
=> RHINENG-8136: remove DeprecateV1V2APIs middleware

base/utils/gin.go, manager/controllers/systems_advisories_view_test.go
`c.Query(key)` claims to be a shortcut for `c.Request.URL.Query().Get(key)` by `gin` documentation. The reality is that `c.Query()` tries to get the value from QueryCache if cache exists, The cache is created with first c.Query() call on given context (might be created with other calls as well).
The problem is with /views apis. The query is added dynamically to `c.Request.URL.RawQuery` there. My guess is that it worked previously because we modified the context `c` with `apiver`... it looks like it stopped working after removal of `apiver` decisions and removal of v2 structs (it works in prod but not in stage) but I haven't tried to trace the exact commit.
IMO it should be safer to use `c.Request.URL.Query().Get(key)`
=> RHINENG-8716: fix dynamically set limit in c.Request.URL

manager/controllers/systems_advisories_view.go, manager/controllers/utils.go
Currently, total_items shows number of items after `Limit` is applied by `ListCommon`, we'd like to show real total items.
Separate `tx.Limit` from `ListCommon` so the limit can be applied to a subquery after we get the total count.
What do you think?
=> RHINENG-8717: fix total count in /views

docs/v3/openapi.json, manager/controllers/advisories.go, manager/controllers/advisories_test.go, manager/controllers/baseline_systems.go, manager/controllers/package_systems_test.go, manager/controllers/structures.go, manager/controllers/systems_ids_test.go, manager/controllers/utils.go
Currently some */ids* endpoints respond with a list of ids in `ids` section, other endpoints respond with `ids` and `data` sections. After the change, all endpoint responses should have both `ids` and `data` sections, even if the data section consists only of `IDPlain`s.
=> RHINENG-8389: make /ids responses consistent

base/models/models.go, database_admin/migrations/125_yum_checksum.down.sql, database_admin/migrations/125_yum_checksum.up.sql, database_admin/schema/create_schema.sql, listener/upload.go
There were a few issues with the current query
- First can be used only on Model
- can't load to map[string]string, gorm showing weird error about sql.Scan called but Next not used
- need to cast jsonb to text for `digest` and encode the hex value
Second issue is that digest can't be used for yum_updates as it contains a hash map and order of fields is not deterministic
=> fix checksum comparison in listener

manager/controllers/common_attributes.go
change gorm column name of groups and tags so we are able to sort by `sort=groups` and `sort=tags` (`sort=tags` isn't documented but I changed it) it was possible to sort with `sort=groups_json` (breaks sorting in prod) and `sort=tags_json`
I would expect that sorting should work according to attribute name in json, I tried to changed that to use the json attribute name instead of gorm column name but that broke osname, osmajor, osminor sorts...
=> RHINENG-9077: fix sorting by groups and tags

base/database/testing.go, base/models/models.go, base/mqueue/template_event.go, database_admin/migrations/126_template_environment.down.sql, database_admin/migrations/126_template_environment.up.sql, database_admin/schema/create_schema.sql, dev/test_data.sql, listener/template_test.go, listener/templates.go, platform/platform.go
=> RHINENG-10439: store environment id for template

docs/v3/openapi.json, manager/controllers/advisories.go, manager/controllers/advisory_systems.go, manager/controllers/baseline_systems.go, manager/controllers/baselines.go, manager/controllers/package_systems.go, manager/controllers/package_versions.go, manager/controllers/packages.go, manager/controllers/system_advisories.go, manager/controllers/system_packages.go, manager/controllers/systems.go, manager/controllers/systems_advisories_view.go, manager/controllers/systemtags.go, manager/controllers/template_systems.go
=> RHINENG-10747: limit=-1 is not allowed

base/database/utils.go, docs/v3/openapi.json, manager/controllers/advisory_systems.go, manager/controllers/advisory_systems_export_test.go, manager/controllers/common_attributes.go, manager/controllers/package_systems.go, manager/controllers/package_systems_export_test.go, manager/controllers/system_detail.go, manager/controllers/systems.go, manager/controllers/systems_export_test.go
=> RHINENG-10237: show template name and id in systems endpoints

listener/templates.go
=> RHINENG-10827: unassign systems before template delete

base/rbac/rbac.go, base/rbac/rbac_test.go, manager/middlewares/rbac.go, manager/middlewares/rbac_test.go, platform/rbac.go
=> RHINENG-11257: fix attributeFilter parsing for string value

manager/controllers/advisory_detail.go
=> RHINENG-11929: return errata from db if it does not have attributes

manager/middlewares/rbac.go
current log fails with
```
Unable to read entry, failed to marshal fields to JSON, json: unsupported type: func() (io.ReadCloser, error)
Failed to fire hook: failed to marshal fields to JSON, json: unsupported type: func() (io.ReadCloser, error)
```
=> RHINENG-11685: debug only gin context request header

evaluator/evaluate_advisories.go
- introduce `advisories-load` and `advisories-evaluate` instead of the missing `advisories-processing`
- similarly to `lazy-package-save`, add `advisories-lazy-save`
- fix missing `installable`, `applicable`, and `fixed` counter updates
=> RHINENG-11978: fix missing metrics after evaluator refactor

manager/middlewares/limits.go, manager/middlewares/rbac.go, manager/middlewares/timeout.go
This needs to get debugged in stage because local/ephemeral uses platform mock. When the mock is used, gzipping works as expected.
=> RHINENG-11685: add temp debug logs for middleware

manager/middlewares/limits.go, manager/middlewares/rbac.go, manager/middlewares/timeout.go
=> RHINENG-11685: modify temp debug logging

base/errors.go, base/mqueue/mqueue.go, evaluator/evaluate.go, evaluator/evaluate_baseline.go, evaluator/remediations.go, listener/upload.go, listener/upload_test.go, manager/middlewares/authentication.go
=> RHINENG-9452: refactor error handling

manager/manager.go, manager/middlewares/gzip.go, manager/middlewares/rbac.go
=> RHINENG-11685: gzip middleware with logging

base/database/baseline.go
```
panic: runtime error: index out of range [0] with length 0
goroutine 261071 [running]:
app/base/database.GetBaselineConfig(0xc03a4e1040)
/go/src/app/base/database/baseline.go:31 +0x445
app/evaluator.limitVmaasToBaseline(0x0?, 0xc03a565d40)
/go/src/app/evaluator/evaluate_baseline.go:12 +0x2a
app/evaluator.evaluateWithVmaas(0x19f48b8?, 0xc03a4e1040, 0xc03a4e1040?)
/go/src/app/evaluator/evaluate.go:285 +0x4c
app/evaluator.evaluateInDatabase({0x19f48b8, 0xc00082e320}, 0xc0004d5d50, {0xc015ce2a50, 0x24})
/go/src/app/evaluator/evaluate.go:230 +0xa6
app/evaluator.Evaluate({0x19f48b8, 0xc00082e320}, 0xc023e47550?, {0xc015ce2a50, 0x24}, {0xc00004a011, 0x6})
/go/src/app/evaluator/evaluate.go:146 +0x21c
app/evaluator.runEvaluate.func1()
/go/src/app/evaluator/evaluate.go:186 +0x6c
created by …
```
=> RHINENG-12299: fix index out of range error

Dockerfile, database_admin/migrations/129_create_pg_repack.up.sql, database_admin/schema/create_schema.sql, deploy/clowdapp.yaml, dev/database/Dockerfile, docs/admin/openapi.json, main.go, manager/routes/routes.go, tasks/repack/repack.go, turnpike/controllers/admin.go
=> RHINENG-10032: implement pg_repack job and admin API

base/candlepin/candlepin.go, base/utils/config.go, manager/config/config.go, manager/controllers/template_systems_delete.go, manager/controllers/template_systems_update.go
=> RHINENG-9505: candlepin improvements

Dockerfile
=> RHINENG-12554: rebase images to ubi9

deploy/clowdapp.yaml, tasks/repack/repack.go
=> RHINENG-10032: fix repack job db user

database_admin/migrations/131_remove_advisory_old_package_data.up.sql, database_admin/schema/create_schema.sql
=> RHINENG-13371: remove old package_data from advisory_metadata

base/mqueue/mqueue_impl_gokafka.go, base/utils/http.go, database_admin/schema_test.go, platform/inventory.go
=> RHINENG-13300: fix disabled gosec rules

.tekton/patchman-engine-push.yaml
This reverts commit d9dd52410d09dfeb3d1eabd4d71fd869e89f67c6.
fixes failed konflux build
=> fix failed konflux build

base/notification/notification.go, evaluator/evaluate.go, evaluator/notifications.go, evaluator/notifications_test.go
=> RHINENG-13828: add system tags to notification context

database_admin/migrations/132_on_system_update_no_lock.up.sql, database_admin/schema/create_schema.sql, deploy/clowdapp.yaml, main.go, manager/controllers/advisories.go, tasks/cleaning/clean_advisory_account_data.go, turnpike/controllers/admin.go
=> RHINENG-14390: rewrite on_system_update trigger without locking

manager/controllers/template_systems_delete.go, manager/controllers/template_systems_update.go
=> RHINENG-13518: assign only system which are in candlepin

docs/admin/openapi.json, scripts/check-openapi-docs.sh
=> RHINENG-14390: openapi spec for /clean-advisory-account-data

base/utils/gin.go, base/utils/identity.go, dev/scripts/identity-system.sh, docs/docs_test.go, docs/v3/openapi.json, go.mod, go.sum, manager/controllers/template_subscribed_systems_update.go, manager/controllers/template_subscribed_systems_update_test.go, manager/controllers/template_systems_update.go, manager/middlewares/authentication.go, manager/middlewares/authentication_test.go, manager/routes/routes.go, platform/platform.go
=> RHINENG-14351: add system authenticated API for templates

docs/v3/openapi.json, manager/controllers/template_subscribed_systems_update.go, manager/controllers/template_systems_update.go, manager/middlewares/authentication.go
=> RHINENG-14351: fix candlepin API status handling 

base/database/testing.go, listener/upload_test.go, manager/controllers/baseline_create.go, manager/controllers/baseline_update.go, manager/controllers/baseline_update_test.go, manager/controllers/systems_advisories_view.go, manager/controllers/template_systems_delete_test.go, manager/controllers/template_systems_update_test.go
inventory_id::text IN (?) which prevents use of indexes correct cast is the other way: inventory_id IN (?::uuid)
=> RHINENG-14936: fix wrong type casting in db

base/notification/notification.go, base/utils/config.go, deploy/clowdapp.yaml, evaluator/evaluate.go, evaluator/notifications.go, evaluator/notifications_test.go
=> RHINENG-14896: fix host_url in notifications

Dockerfile
When running in RHEL9, the /usr/lib64/ossl-modules directory is also required to be copied into the micro image. Without it, FIPS errors occur during the database init phase of the startup.
=> task: Add required FIPS dependency

renovate.json
default setting is 'auto' which causes that renovate decides to use semantic commits based on last commits. It happens that closed PRs updating major versions are re-opened due to commits having different format
=> RHINENG-16833: disable semantic commits by renovate
