RedHatInsights/patchman-engine

- README.md
- docker-compose.yml
- prototypes/go/app/core/config.go
- prototypes/go/app/listener/message.go
- prototypes/go/app/utils/rpm.go
- prototypes/go/app/utils/rpm_test.go
https://projects.engineering.redhat.com/browse/SPM-1
- added full nevra parsing using regex
- optimized parsing with parallelism
- added `security_opt` to docker-compose to allow selinux
> Added NEVRA parsing using regex

- dev/benchmark-simple.sh
- dev/collect-stats.sh
- docker-compose.yml
- prototypes/py/db.py
- prototypes/py/handler.py
- prototypes/py/listener.py
- prototypes/py/main.py
- prototypes/py/prototype.api.yaml
Add basic script for simple benchmarks, fix python to work correctly with this script
> Create benchmark scripts

- base/vmaas_client/client.go
- base/vmaas_client/client_test.go
- base/vmaas_client/structures.go
- base/vmaas_client/vmaas_mock.go
> Added VMaaS client

- Dockerfile.test
- base/core/config.go
- base/utils/gin.go
- dev/scripts/systems_list.sh
- docker-compose.test.yml
- docker-compose.yml
- manager/controllers/advisories.go
- manager/controllers/advisory_systems.go
- manager/controllers/health_test.go
- manager/controllers/paging.go
- manager/controllers/paging_test.go
- manager/controllers/structures.go
- manager/controllers/system_advisories.go
- manager/controllers/system_detail.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/test_utils.go
- manager/controllers/utils.go
- scripts/go_test_db.sh
- scripts/test_data.sql
> List systems from db and return via API

- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_test.go
- manager/controllers/system_detail.go
- manager/controllers/system_detail_test.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
- scripts/test_data.sql
- Rest of manager endpoints connected to database.
- It does not include filtering with rh-account (another ticket).
- Not complete counting of system advisories. It requires bigger db schema update (another ticket).
> Connected API to data in database

- base/models/models.go
- database/schema/create_schema.sql
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- platform/vmaas.go
- Updated SQL schema
- Updated model in go
- Added test
> Added counters for specific advisory types

- base/database/database.go
- base/models/models.go
- listener/listener.go
- listener/upload.go
- listener/upload_test.go
Moves code which processes uploads to separate file.  Implements process to get system_profile from inventory, create VMaaS request, And store both RHAccount and SystemProfile into the database.
Tests for parts which do not require external APIs are implemented.
> Save hosts in listener

- docs/docs.go
- docs/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_systems.go
- manager/controllers/system_advisories.go
- manager/controllers/system_detail.go
- manager/controllers/systems.go
- manager/middlewares/swagger.go
- Moves openapi spec to path expected by the platform.
- Adds operationId with human-readable operation description as dictated by platform spec.
> Docs fixes

- conf/test.env
- docker-compose.test.yml
- listener/evaluate.go
- listener/upload.go
- listener/upload_test.go
- Evaluation moved to separate file and method.
- Added kafka message parsing test.
- Added upload handler test.
> Upload tests

- .travis.yml
- README.md
- docker-compose.test.yml
- scripts/go_test.sh
- scripts/go_test_on_ci.sh
Run unit tests on Travis. I don't have rights to enable the repo on Travis, can some of you please do it? - https://travis-ci.org/RedHatInsights/patchman-engine/
Also adds upload to codecov.io (only when running on Travis).
Test run on https://travis-ci.org/mkoura/patchman-engine/builds/633258180
> Run tests on Travis

- listener/listener.go
Add logging to listener in order to diagnose restarts.
> Add logging to kafka

- Dockerfile.test
- base/database/setup.go
- evaluator/evaluate.go
- listener/upload.go
- listener/upload_test.go
- manager/controllers/advisories.go
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_systems.go
- manager/controllers/health.go
- manager/controllers/system_advisories.go
- manager/controllers/system_detail.go
- manager/controllers/systems.go
- manager/controllers/utils.go
- manager/middlewares/authentication.go
- manager/middlewares/logger.go
- platform/platform.go
- scripts/go_test_on_ci.sh
- vmaas_sync/advisory_sync.go
- added automatic checking
- fixed lint hints
> Added golangci-lint checker with default settings

- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/system_advisories.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
- Adds a method which by default applies sort by internal ID, and allows adding new fields to sort by easily
> Add basic sorting

- database/schema/init_schema.sh
- openshift/deploy/database.yml
- openshift/deploy/listener.yml
- openshift/deploy/manager.yml
- openshift/deploy/vmaas_sync.yml
- openshift/secrets/patchman-database-passwords.yml
- Listener does almost nothing, Current implementation even less so. but we need multiple pods
- Database runs on 300MB RAM right now, without any traffic
> Make resource limits more reasonable

- database/schema/create_schema.sql
- evaluator/evaluate.go
- evaluator/evaluate_test.go
- evaluator/metrics.go
- listener/delete.go
- listener/listener.go
- listener/metrics.go
- listener/upload.go
- received messages metric
- evaluation duration metric
- updates count metric, etc
> Added received messages metric to listener

- conf/evaluator.env
- conf/listener.env
- conf/test.env
- platform/entrypoint.sh
Changed evaluator topic to conform what we have in platform kafka
https://github.com/RedHatInsights/platform-mq/pull/38
> Change evaluator topic 

- database/migrate.sh
- database/migrations/002_base_schema.up.sql
- database/migrations/005_adv_severity.up.sql
- database/schema/create_schema.sql
- database/schema/init_schema.sh
- evaluator/evaluate.go
- evaluator/metrics.go
- openshift/deploy/_cfg.yml
- openshift/deploy/database.yml
- openshift/deploy/evaluator.yml
- vmaas_sync/advisory_sync.go
Fixes which had to be performed in order to get large batch of PRs deployed on CI
Includes:
- Making existing migrations more resilient to schema mismatches
- Automatically deploying Database through migrations
- Fixes to openshift templates
- Fixes to evaluator component
> CI deployment fixes

- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/structures.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_test.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/test_utils.go
- manager/controllers/utils.go
- Unifies different `meta` fields.
- Handles limit, offset, sort in common function
> Unified list meta field & limit, offset, sort handling

- README.md
- base/database/setup.go
- scripts/sync.sh
- vmaas_sync/advisory_sync.go
- vmaas_sync/debug_api.go
- vmaas_sync/metrics.go
- vmaas_sync/vmaas_sync.go
- also added syncing duration Prometheus metric
> Enable to call vmaas_sync - sync manually

- evaluator/evaluate.go
> Add inventoryID to error log in evaluation

- evaluator/evaluate.go
- evaluator/metrics.go
- do not call VMaaS when package_list len is 0
- added new error states to evaluation
- added evaluation parts duration measurements
> Check packages before requesting VMaaS updates - evaluation

- listener/common_test.go
- listener/delete_test.go
- listener/upload.go
- listener/upload_test.go
- Added updated rows count. Throw error when this number == 0
> Added update check to listener

- listener/upload.go
> Manually check if there are any DNF modules

- conf/common.env
- go.mod
- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/filter.go
- manager/controllers/filter_test.go
- manager/controllers/paging.go
- manager/controllers/structures.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_test.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
Further work depending on #82 .
> Implement Filter parsing & SQL generation

- manager/controllers/advisories.go
- manager/controllers/advisory_systems.go
- manager/controllers/system_advisories.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
- Include `stale` field in responses.
- Add default filter capability
- Add default filter for returning only `fresh` systems
> System culling changes in manager

- dev/test_data.sql
- evaluator/evaluate_test.go
- manager/controllers/system_advisories.go
- manager/models/models_test.go
- vmaas_sync/metrics_test.go
- show only not patched system advisories
> Ignore patched system advisories

- base/utils/log_test.go
- base/utils/testing.go
- listener/common_test.go
- listener/delete.go
- listener/delete_test.go
- listener/upload.go
- listener/upload_test.go
- added uploadHandler tests for error states
> Improved testing log hook, added uploadHandler tests

- listener/delete.go
- listener/upload.go
> Add missing increments to metric counters

- listener/upload.go
> Fix problem with filtering repos list

- base/utils/core.go
- scripts/psql.sh
- vmaas_sync/advisory_sync.go
- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/vmaas_sync.go
- Added DEFAULT_PAGE_SIZE param
- Added pagination when downloading repos
> Fixed repos downloading

- evaluator/evaluate.go
Move storing of `system_advisories` and `advisory_account_data` into new method. 
Should provide us more granularity,  the label `advisories-processing` will now cover only the processing of reading & processing of the data & label `advisories-store` will cover actual updating of `system_advisories` & `advisory_account_data`
> Evaluator - split updating of database into new method

- go.mod
- go.sum
- fixed go.sum file which was still automatically updated by IDE
- removed not used pq dep
> updated go-deps

- base/base.go
- base/mqueue/mqueue.go
- base/mqueue/mqueue_test.go
- dev/scripts/platform_toggle_upload.sh
- docker-compose.yml
- evaluator/evaluate.go
- evaluator/evaluate_test.go
- listener/listener.go
- listener/listener_test.go
- platform/inventory.go
- platform/platform.go
- also added testing upload loop
> Added Kafka readers closing using WaitGroup

- base/core/config.go
- base/metrics/metrics.go
- base/mqueue/metrics.go
- base/mqueue/mqueue.go
- base/mqueue/mqueue_test.go
- base/utils/gin_test.go
- scripts/wait-for-services.sh
- Added prometheus counters counting Kafka connection read/write errors.
- Fixed TestRunServer test.
- Fixed and unified Kafka connection errors logging.
> Added kafka error Prometheus counter

- evaluator/evaluate.go
Add backof specifically for vmaas returning 503
> master -> stable

- dev/kafka/setup.sh
- listener/events.go
- listener/events_test.go
- listener/listener.go
Handle 'updated' messages from inventory to update display_name
> Handle 'updated' events

- vmaas_sync/metrics.go
- Will allow us to monitor stuck transactions & similar problems
> Add metric for different database processes

- base/database/setup.go
- base/database/testing.go
- base/mqueue/event.go
- base/utils/gin.go
- database_admin/schema_test.go
- docs/openapi.json
- evaluator/evaluate.go
- evaluator/evaluate_test.go
- listener/common_test.go
- listener/events_test.go
- listener/upload.go
- listener/upload_test.go
- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/system_advisories.go
- manager/controllers/systems.go
- manager/controllers/utils.go
- vmaas_sync/advisory_sync_test.go
- vmaas_sync/vmaas_sync_test.go
- updated api docs
- added test
> Added option to return all list items setting limit to -1

- base/mqueue/mqueue.go
There were some issues due to Kafka settings in perf-testing environment. Kafka reader config update solve this problem. I've added options to change Kafka reader config using env vars.
> Added optional KAFKA_READER_MIN_BYTES and KAFKA_READER_MAX_BYTES vars

- Dockerfile.centos
- Dockerfile.rhel8
- Dockerfile.test
- docs/openapi.json
- go.mod
- go.sum
- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/system_advisories.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
- manager/routes/routes.go
- Added endpoints for exporting data
- Endpoints do not support paging, sorting, or filters(TBD)
- Supporting 'application/json' & 'text/csv' content types
- Flat object structure for easy manipulation
> [WIP] Add export feature

- docs/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
- Adds a way to filter exported data, format is preserved between API and export endpoints
> Implement filters for export endpoints

- base/models/models.go
- base/utils/rpm.go
- base/utils/rpm_test.go
- database_admin/migrations/023_jsonb_pkgdata.up.sql
- database_admin/schema/create_schema.sql
- dev/test_data.sql
- docs/openapi.json
- evaluator/evaluate.go
- evaluator/evaluate_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_test.go
- manager/controllers/packages.go
- manager/controllers/packages_test.go
- manager/controllers/system_detail_test.go
- manager/controllers/systems_test.go
- manager/routes/routes.go
- platform/vmaas.go
- scripts/generate_docs.sh
- vmaas_sync/advisory_sync.go
- vmaas_sync/metrics_test.go
- Stores packages as JSONB column
- `/packages` endpoint for account-level data sped up by GIN index
- `/systems/:system_id/packages` for per-system package data.
> Experimental package data implementation

- evaluator/evaluate.go
Fixes an issue introduced in packages PR.
> Revert removing port from evaluator

- base/mqueue/message.go
- base/utils/testing.go
- conf/evaluator_common.env
- dev/kafka/setup.sh
- evaluator/evaluate.go
- evaluator/evaluate_test.go
- evaluator/remediations.go
Depends on https://github.com/RedHatInsights/e2e-deploy/pull/1853
> Send updates to remediations after evaluation

- evaluator/evaluate.go
- evaluator/remediations.go
In order to track down CI errors
> Better error loggging in remediation update push

- base/database/testing.go
- base/models/models.go
- base/utils/rpm.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/package_systems_test.go
- platform/vmaas.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/advisory_sync_test.go
- vmaas_sync/pkg_sync.go
- Implemented package data synchronization during vmaas_sync.
- Restored some schema changes to be removed in another PR, to avoid conflicts
> Implement package syncing in vmaas_sync

- vmaas_sync/advisory_sync.go
- vmaas_sync/pkg_sync.go
There was an issue with errata which do not have any packages.
> Fix syncing errors

- base/utils/rpm.go
- base/utils/rpm_test.go
- database_admin/migrations/028_update_delete.up.sql
- database_admin/schema/create_schema.sql
Fix issues observed with package data in CI.
- We have parsed NEVRAs incorrectly
- `delete_system` sql function was not updated.
> Small fixes, package data bugs.

- docs/openapi.json
- evaluator/evaluate.go
- Changed how we query for packages during evaluation
- Added prometheus metrics for additional evaluation steps
> Package data perf improvements

- database_admin/migrations/029_package_counts.down.sql
- database_admin/migrations/029_package_counts.up.sql
- database_admin/schema/create_schema.sql
- dev/test_data.sql
- evaluator/evaluate.go
- go.mod
- go.sum
- manager/controllers/package_systems_test.go
- manager/controllers/system_detail_test.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- platform/inventory.go
Adds pre-calculated package counts to `system_platform`.
> Add package counts to system endpoints

- Dockerfile.centos
- Dockerfile.rhel8
- scripts/manifest/rpm_list.sh
- updated manifest items prefix
- removed kernel rpm from manifest
> Manifest prefix and kernel item

- Dockerfile.test
- scripts/check-openapi-docs.sh
- scripts/go_test_on_ci.sh
- added generator x in-repo-file checking
> Add pipeline check for openapi.json

- README.md
- database_admin/migrations/030_cyndi_tags.up.sql
- database_admin/schema/create_schema.sql
- dev/scripts/system_detail.sh
- dev/test_data.sql
- evaluator/evaluate_test.go
- listener/upload.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/package_systems_test.go
- manager/controllers/system_advisories_test.go
- manager/controllers/system_detail_test.go
- manager/controllers/system_packages_test.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
- vmaas_sync/repo_based_test.go
- Change dev data to use UUIDS (allows for joining with inventory.hosts table)
- Use tags stored in inventory.hosts table for filtering
> Project cyndi tags implementation

- manager/middlewares/rbac.go
related to rbac-config patch update: https://github.com/RedHatInsights/rbac-config/pull/84
> added support for custom rbac roles

- listener/events.go
- listener/events_test.go
- listener/upload.go
- listener/upload_test.go
- Process uploads on update events.
- Cleanup the listener code
> Fix listener behavior

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
moving from common repository for dashboards to the app repo
> added grafana dashboard configmap

- vmaas_sync/metrics.go
- vmaas_sync/metrics_db.go
- vmaas_sync/metrics_db_test.go
also added database processes metrics got using `pg_stat_activity`
> Added database size and table sizes metrics

- manager/controllers/packages_test.go
- manager/controllers/utils.go
- manager/controllers/utils_test.go
Needed in order to support deeply nested filters syntax.
> Add support for nested query maps

- base/metrics/metrics.go
- docker-compose.yml
- evaluator/evaluate.go
- evaluator/metrics.go
- listener/metrics.go
- vmaas_sync/metrics.go
- vmaas_sync/metrics_db.go
- added evaluation delay metric
- added metrics help strings
- fixed bug in docker-compose.yml (not creating kafka output topic)
> Uploal-evaluation delay metric

- manager/middlewares/rbac.go
> Revert "added support for custom rbac roles"

- evaluator/evaluate.go
- evaluator/evaluate_test.go
We perform left join and in previous PR moved additional join params to where clase, which changed behavior of whole query.
> Fix issue with evaluation

- vmaas_sync/send_messages.go
- vmaas_sync/vmaas_sync.go
> added ENABLE_RECALC_MESSAGES_SEND option to vmaas_sync

- database_admin/migrations/037_delete_system_part.up.sql
- database_admin/schema/create_schema.sql
Probable cause of recent database deadlock
> Update delete_system to take partitioning into account

- base/utils/rpm.go
- evaluator/evaluate.go
Should improve performance by loading less data and overwriting less data.
> Better check to skip writing package updates, reduce loaded columns

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
fixed rds_datasource usage in RDS charts
> grafana update

- base/base.go
- base/models/models.go
- base/mqueue/event.go
- base/utils/rpm.go
- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- database_admin/migrations/037_delete_system_part.up.sql
- database_admin/schema/create_schema.sql
- docs/openapi.json
- evaluator/evaluate.go
- listener/upload.go
- listener/upload_test.go
- manager/controllers/advisories.go
- manager/controllers/advisory_systems.go
- manager/controllers/package_detail.go
- manager/controllers/package_systems.go
- manager/controllers/packages.go
- manager/controllers/system_advisories.go
- manager/controllers/system_packages.go
- manager/controllers/systems.go
- manager/manager.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/pkg_sync.go
- vmaas_sync/send_messages.go
Fixed partitioning deletes
Better logging for vmaas-sync
...
> Release 1.3.7

- docs/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisory_systems.go
- manager/controllers/package_systems.go
- manager/controllers/packages.go
- manager/controllers/system_advisories.go
- manager/controllers/system_packages.go
- manager/controllers/systems.go
- manager/controllers/utils.go
Temporary solution. In the future we'll need to migrate away from currently used framework
> Add docs for workload filters

- docs/openapi.json
- evaluator/evaluate.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_test.go
We had missing attribute on this endpoint. Needed for package systems table.
> Add missing attribute to package systems

- base/models/models.go
- database_admin/migrations/039_system_package_updatable.up.sql
- database_admin/schema/create_schema.sql
- docs/openapi.json
- evaluator/evaluate.go
- manager/controllers/packages.go
- manager/controllers/system_packages.go
- manager/controllers/systems.go
- Some more optimizations for packages
- Fix for missing system_package entries
> Stable <- Master

- .github/workflows/unittests.yml
Travis is slow, it'd be nice to at least have github workflows for now.
> Run unit tests on github workflows

- database_admin/migrations/042_delete_packages_old.up.sql
- database_admin/schema/create_schema.sql
- vmaas_sync/metrics_db_test.go
- Removes old table
- Redirects all code to new one
> System-packages re-partition, part 2

- listener/upload.go
- some systems in database don't have reporter assigned. Trying to investigate why.
> added metric and log message for unknown reporter

- evaluator/evaluate.go
- evaluator/evaluate_test.go
- go.mod
- go.sum
- listener/upload.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/pkg_sync.go
- vmaas_sync/repo_based.go
to filter out multiple version of installonly packages
> use latest_only option for vmaas api

- docker-compose.yml
- to better test test migrations
> added db-data volume to docker-compose example

- vmaas_sync/advisory_sync_test.go
- vmaas_sync/pkg_sync.go
We have some packages with no associations to advisories in CI
> Update package data on sync

- listener/upload.go
forgotten .Inc() calling added
> fixed skipped reporter metric increment

- dev/scripts/env.sh
- after updating testing accounts in test_data.sql it's needed to update account setting into the env variable ACCOUNT_NUMER in `./dev/scripts/env.sh`
> fixed setting up testing account

- base/utils/identity.go
- base/utils/identity_test.go
- go.mod
- go.sum
- manager/middlewares/authentication.go
- manager/routes/routes.go
- platform/platform.go
Use platform-go-middleware for parsing identity, Add a new api group accepting only associate auth, which comes from turnpike.
> Add privileged interface

- database_admin/config.sql
fixing
psql:./database_admin/config.sql:2: ERROR:  database "patchman" does not exist
> log slow statements in test/ci/qa

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> added namespace to Grafana board

- .github/workflows/open_api_spec.yml
- .github/workflows/unittests.yml
> New spec check workflow

- conf/database_admin.env
- database_admin/entrypoint.sh
- database_admin/migrate.go
to enable to specify desired db version for migration
> added optional SCHEMA_MIGRATION=int db_admin cfg variable

- conf/database_admin.env
- database_admin/update.sh
- allowing to drop and recreate schema (of specific version when
SCHEMA_MIGRATION is used in addition).
> added optional env var RESET_SCHEMA to database-admin

- database_admin/migrations/045_bulk_delete.down.sql
- database_admin/migrations/045_bulk_delete.up.sql
- database_admin/migrations/046_delete_yupana.up.sql
- database_admin/schema/create_schema.sql
- Add stored procedure for bulk delete
- Update delete_culled_systems to use this method
- Manually delete yupana systems in batches of 5000
> Bulk delete

- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/send_messages.go
> include AccountID into recalc messages

- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/send_messages.go
include AccountID into recalc messages
> master to stable: fix vmaas-sync recalc

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- dashboards/grafana-json-to-yaml.sh
into database table size graph
> added system_advisories_sum and system_platform_sum

- base/database/utils.go
- evaluator/evaluate.go
- manager/controllers/advisories.go
- manager/controllers/advisory_systems.go
- manager/controllers/package_detail.go
- manager/controllers/package_systems.go
- manager/controllers/packages.go
- manager/controllers/system_advisories.go
- manager/controllers/system_detail.go
- manager/controllers/system_packages.go
- manager/controllers/systems.go
- manager/controllers/systems_advisories_view.go
Cleanup the SQL queries used across the manager.
> Query cleanup

- docs/openapi.json
- manager/controllers/systems_advisories_view.go
> Fix routes on views endpoints

- docs/openapi.json
- evaluator/evaluate.go
- manager/controllers/advisories_export_test.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_test.go
- manager/controllers/systems_advisories_view.go
- vmaas_sync/metrics_cyndi.go
- cve counts info added to /*advisories
- vmaas-sync tags metrics improvement
- skip gpg-pubkey in evaluator
- fixed api-doc
> master to stable 1.6.1-2

- manager/controllers/system_detail.go
- manager/controllers/utils.go
- Issue created during query cleanup. Joining with inventory is mandatory in this endpoint
> Fix system detail missing join

- base/database/utils.go
> SPM-631: performance improvements

- database_admin/migrations/058_mark_stale_fix.down.sql
- database_admin/migrations/058_mark_stale_fix.up.sql
- database_admin/schema/create_schema.sql
- vmaas_sync/system_culling.go
- vmaas_sync/system_culling_test.go
- Was missing order by clause in locking select
- Created index for inventory_id in system_platform
- added max_systems parameter to mark_system_stale
> Fix a lot of things

- manager/middlewares/rbac.go
We need to add some resource, so I've added "system".
> added system resource to rbac perms

- manager/controllers/utils.go
Inventory handles the `null` string as actual null value when passed as tag namespace
> Clean up tag handling

- dev/test_data.sql
- manager/controllers/advisory_systems.go
- manager/controllers/package_systems.go
- missing stale systems filter in advisory_systems
- Wrong join in package_systems
> Fix query bugs

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- culling data
- two evaluations interval
> added new charts to grafana

- base/database/testing.go
- base/models/models.go
- database_admin/migrations/060_thirdparty.down.sql
- database_admin/migrations/060_thirdparty.up.sql
- database_admin/schema/create_schema.sql
- evaluator/evaluate.go
- evaluator/evaluate_test.go
> thirdparty repo flag for API

- vmaas_sync/admin_api.go
- vmaas_sync/auth/turnpike.go
- vmaas_sync/vmaas_sync.go
Will require changes to deployments
> Turnpike vmaas sync

- base/database/testing.go
- base/models/models.go
- database_admin/migrations/061_opt_out.down.sql
- database_admin/migrations/061_opt_out.up.sql
- database_admin/schema/create_schema.sql
- dev/test_data.sql
- listener/upload_test.go
- vmaas_sync/metrics.go
- vmaas_sync/metrics_test.go
Remove the `opt_out` column. Change its uses to the `stale` column.
> Remove opt_out

- docs/openapi.json
- manager/controllers/advisories.go
- manager/manager.go
Just provides a link to a public wiki.
> Add link to filters documentation in apidoc

- go.mod
- go.sum
- listener/common_test.go
- listener/upload.go
- platform/inventory.go
> SPM-768: use rhsm release if available

- manager/controllers/system_packages.go
as this field is not displayed in UI so it doesn't make sense to search in
> excluded description field from search in system_packages.go

- go.sum
> updated go.sum with missing item

- dev/test_data.sql
- manager/controllers/package_detail_test.go
- manager/controllers/packages_export_test.go
- manager/controllers/packages_test.go
- platform/vmaas.go
- fixed typo
- extended summary and description test data
- split big test to multiple smaller ones
- extended tests of "search" cases
> Tests updates

- README.md
> updated status link in README, replaced Travis with GitHub actions

- base/mqueue/event.go
- base/mqueue/mqueue_test.go
- evaluator/evaluate.go
- evaluator/evaluate_test.go
- vmaas_sync/send_messages.go
- vmaas_sync/vmaas_sync_test.go
> Add message for bulk evaluation in recalc

- vmaas_sync/admin_api.go
- vmaas_sync/vmaas_sync.go
to fix not working /sync.sh and /re-calc.sh in CI and QA
> SPM-824 added ENABLE_TURNPIKE_AUTH=false to vmaas_sync

- base/mqueue/mqueue_test.go
- base/utils/gin_test.go
- base/utils/testing.go
- evaluator/evaluate_test.go
- listener/listener_test.go
- vmaas_sync/vmaas_sync_test.go
> SPM-727 improved testing AssertWait function

- vmaas_sync/admin_api.go
- vmaas_sync/vmaas_sync.go
> SPM-736 repo-sync added to manual sync handler in vmaas-sync

- evaluator/evaluate.go
> SPM-736: gorm can't convert int to bool

- base/database/setup.go
- conf/common.env
> Added optional DB_DEBUG=false option to debug database transactions

- dev/test_generate_data.sql
> added "package_name" and "package" into "test_generate_data.sql"

- evaluator/evaluate_packages.go
> SPM-830 fix nil pointer in evaluation

- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
> SPM-830 Fill lazy package summary and description

- evaluator/evaluate_packages.go
- vmaas_sync/repo_based.go
> SPM-830 Fixed "installed" value counting

- base/database/testing.go
- base/utils/openapi.go
- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/evaluate_test.go
> SPM-830 fix installed packages

- base/database/testing.go
- vmaas_sync/advisory_sync_test.go
- vmaas_sync/metrics.go
- vmaas_sync/metrics_test.go
- vmaas_sync/vmaas_sync_test.go
> SPM-846 added packages metrics to vmaas_sync

- README.md
- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> Updated Grafana config, added packages metrics

- README.md
- base/metrics/metrics.go
- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- docs/openapi.json
- manager/manager.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/metrics_test.go
> stable 1.9.2

- base/utils/openapi.go
- evaluator/evaluate_advisories_test.go
- evaluator/evaluate_packages_test.go
- evaluator/remediations_test.go
- listener/upload.go
- listener/upload_test.go
- platform/vmaas.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/advisory_sync_test.go
- vmaas_sync/repo_based.go
so it's easy to find them in one place
> make "alias" for vmaa.Ptr*() functions in utils

- listener/listener_test.go
> SPM-728 Remove randomly failing test "TestRunReaders"

- go.mod
- go.sum
> SPM-853 Update vmaas client to v0.12.0

- evaluator/evaluate.go
- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/package_name_cache.go
- evaluator/package_name_cache_test.go
> SPM-868 fixed package-name-cache concurrent access

- vmaas_sync/advisory_sync.go
- vmaas_sync/vmaas_sync.go
> SPM-853 Refactored "vmaas_sync/advisory_sync.go" process

- evaluator/evaluate_packages.go
it will make system_package table smaller and faster
> SPM-866: make update_data unique

- vmaas_sync/pkg_sync.go
> SPM-853 Refactored "vmaas_sync/pkg_sync.go"

- go.mod
- go.sum
> SPM-853 Update vmaas client to v0.13.0

- manager/controllers/advisories.go
- manager/controllers/system_advisories.go
... and system_advisory search
> Remove description from advisory search

- listener/events.go
> Log parsing errors in listener

- base/database/utils.go
> simplified Packages query, removed sub-selects

- base/utils/core.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/advisory_sync_test.go
- vmaas_sync/package_sync.go
- vmaas_sync/package_sync_test.go
- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/repo_sync.go
- vmaas_sync/vmaas_sync.go
> SPM-853 added sync duration info logs

- .golangci.yml
> SPM-885 replaced deprecated "scopelint" linter with "exportloopref"

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.10.0

- listener/upload.go
- listener/upload_test.go
> SPM-891 Enabled "third_party" in evaluation vmaas request.

- base/mqueue/event.go
- listener/listener.go
- listener/upload.go
- listener/upload_test.go
- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/send_messages.go
> Create batch upload eval events not single event for every system

- base/utils/vmaas.go
- evaluator/evaluate.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/package_sync.go
- vmaas_sync/package_sync_test.go
- vmaas_sync/repo_based.go
- vmaas_sync/vmaas_sync.go
> SPM-887 use retry for vmaas-sync vmaas calls

- .gitignore
- base/database/utils.go
- go.mod
- go.sum
- listener/common_test.go
- listener/events_test.go
- listener/upload.go
- platform/inventory.go
- platform/vmaas.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/advisory_sync_test.go
- vmaas_sync/package_sync.go
- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/repo_sync.go
- vmaas_sync/vmaas_sync.go
- vmaas_sync/vmaas_sync_test.go
> update patchman-clients to v0.14.0

- .github/pull_request_template.md
- evaluator/evaluate.go
- listener/upload.go
- listener/upload_test.go
> SPM-891 Use "third_party" in vmaas call if needed only

- manager/middlewares/authentication.go
> Fix detection of unknown account

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.11.1

- base/base.go
- evaluator/evaluate.go
> Use optimistic updates

- vmaas_sync/advisory_sync.go
> Fix advisory sync

- database_admin/migrations/065_epel_changes.down.sql
- database_admin/migrations/065_epel_changes.up.sql
- database_admin/schema/create_schema.sql
> Relax schema constraints for EPEL advisories

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.0

- Dockerfile.centos
- Dockerfile.rhel8
- Dockerfile.test
- docker-compose.test.yml
- docker-compose.yml
- scripts/generate_docs.sh
- scripts/manifest/generate.sh
- scripts/manifest/rpm_list.sh
> SPM-910 Revert dockerfiles updates due to failing osd3 build

- manager/routes/routes.go
> Swap RBAC and account check order

- base/utils/config.go
- base/utils/log.go
- deploy/clowdapp.yaml
- evaluator/evaluate.go
- evaluator/remediations.go
- listener/listener.go
- manager/middlewares/rbac.go
- vmaas_sync/vmaas_sync.go
> SPM-674 Support Kafka dependent components

- base/database/testing.go
- manager/controllers/advisories.go
- manager/controllers/packages.go
- manager/controllers/packages_export_test.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
> removed useless "nolint: lll" comments

- go.mod
- go.sum
> new clowder fixes 'open : no such file or directory'

- Dockerfile.centos
- Dockerfile.rhel8
- scripts/check-dockercomposes.sh
> shrink runtime image +100MB by removing dnf cache

- vmaas_sync/refresh.go
- vmaas_sync/vmaas_sync.go
> SPM-922 Periodically refresh package cached counts

- base/mqueue/mqueue.go
- base/mqueue/mqueue_impl_confluentic.go
- base/mqueue/mqueue_impl_gokafka.go
- base/mqueue/mqueue_test.go
- base/utils/config.go
- conf/common.env
- evaluator/evaluate.go
- evaluator/remediations.go
- go.mod
- go.sum
- listener/listener.go
- platform/platform.go
- vmaas_sync/vmaas_sync.go
> SPM-911 Add kafka authentication support

- Dockerfile.centos
- Dockerfile.rhel8
- scripts/generate_docs.sh
to make script usable and fedora, there is no platform-python command
> Use python3 symlink in ./scripts/generate_docs.sh

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.1

- Dockerfile.centos
- Dockerfile.rhel8
fixing
/api/patch/v1/openapi.json  returning 404
> add openapi.json to runtime image

- docs/openapi.json
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_advisories_export_test.go
- manager/routes/routes.go
Add export endpoints for detail lists.
> Detail export endpoints

- go.mod
- go.sum
SteveHNH has fixed an issue in this library that caused some missing logs
> SPM-980: Update platform-go-middlewares

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.2

- docs/openapi.json
- manager/controllers/advisories_export.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/packages_export.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_packages.go
- manager/controllers/system_packages_export.go
- manager/controllers/system_packages_export_test.go
- manager/controllers/systems_export.go
- manager/routes/routes.go
> SPM-989: Added package level detail exports

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.3

- base/metrics/metrics.go
- docs/openapi.json
- manager/controllers/advisories_export.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/packages_export.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_packages.go
- manager/controllers/system_packages_export.go
- manager/controllers/system_packages_export_test.go
- manager/controllers/systems_export.go
- manager/manager.go
- manager/routes/routes.go
- scripts/wait-for-services.sh
> Stable 1.12.3

- base/database/utils.go
- vmaas_sync/refresh_advisory_caches.go
- vmaas_sync/refresh_advisory_caches_test.go
- vmaas_sync/vmaas_sync.go
- ADVISORY_CACHES_WAIT_SECONDS
- ENABLE_REFRESH_ADVISORY_CACHES
> SPM-831: Added advisory caches refresh job to vmaas-sync

- docs/openapi.json
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/package_systems_test.go
> SPM-989: Added "display_name" to "package_systems_(export)" endpoints

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.4

- base/database/testing.go
- base/database/utils.go
- base/metrics/metrics.go
- docs/openapi.json
- evaluator/evaluate.go
- evaluator/evaluate_packages.go
- evaluator/evaluate_test.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/package_systems_test.go
- manager/manager.go
- vmaas_sync/refresh_advisory_caches.go
- vmaas_sync/refresh_advisory_caches_test.go
- vmaas_sync/vmaas_sync.go
> stable 1.12.4

- .golangci.yml
- base/utils/http.go
- database_admin/migrate.go
- database_admin/schema_test.go
- manager/controllers/filter.go
- platform/vmaas.go
- vmaas_sync/admin_api.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/advisory_sync_test.go
- vmaas_sync/metrics.go
- vmaas_sync/metrics_cyndi.go
- vmaas_sync/metrics_cyndi_test.go
- vmaas_sync/metrics_db.go
- vmaas_sync/metrics_db_test.go
- vmaas_sync/metrics_test.go
- vmaas_sync/package_sync.go
- vmaas_sync/package_sync_test.go
- vmaas_sync/refresh.go
- vmaas_sync/refresh_advisory_caches.go
- vmaas_sync/refresh_advisory_caches_test.go
- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/repo_sync.go
- vmaas_sync/send_messages.go
- vmaas_sync/system_culling.go
- vmaas_sync/system_culling_test.go
- vmaas_sync/vmaas_sync.go
- vmaas_sync/vmaas_sync_test.go
> SPM-798: updated .golangci.yml - replaced 'golint' with 'revive' 

- manager/controllers/packages.go
- manager/controllers/packages_test.go
> SPM-896: Ensured /packages empty response [] (not "null")

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> SPM-1005: Added "Latency uptime" metric to grafana board

- docs/openapi.json
- evaluator/evaluate_packages.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_advisories_export_test.go
> SPM-989: Remove unnecessary attributes from export endpoints

- docs/openapi.json
- manager/controllers/package_systems_export.go
- manager/controllers/system_packages_export.go
> SPM-989: Remove paging from export endpoint docs

- base/utils/config.go
> SPM-984: Include DB_SSLROOTCERT var to printed clowder params

- base/utils/config.go
- deploy/clowdapp.yaml
because PR CI fails waiting for this service to be ready
> SPM-674: Clowder deploy fixes

- docs/openapi.json
- manager/controllers/package_systems.go
- manager/controllers/package_versions.go
- manager/controllers/package_versions_test.go
- manager/routes/routes.go
> SPM-915: Added "package_versions" endpoint.

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.5

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.6

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> SPM-1005: Grafana update, set "Latency uptime" range to 30d

- base/core/config.go
- base/utils/core.go
- base/utils/rpm.go
- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/package_cache.go
- evaluator/package_cache_test.go
- platform/vmaas.go
> SPM-1034: fix package cache epoch issue

- deploy/clowdapp.yaml
- scripts/try_export_clowder_params.sh
This gives a chance to see Clowder-provided params in logs.
> SPM-1022: Enable to print Clowder params (SHOW_CLOWDER_VARS=true)

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.7

- base/core/config.go
- base/metrics/metrics.go
- base/utils/core.go
- base/utils/rpm.go
- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- deploy/clowdapp.yaml
- docs/openapi.json
- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/package_cache.go
- evaluator/package_cache_test.go
- manager/manager.go
- platform/vmaas.go
- scripts/try_export_clowder_params.sh
> stable 1.12.7

- docs/openapi.json
- manager/controllers/advisory_systems_export.go
- manager/controllers/package_systems_export.go
- manager/controllers/packages_export.go
- manager/controllers/systems_export.go
> SPM-1009: Unify filtering on export endpoints

- base/utils/core.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_advisories_export_test.go
- manager/controllers/system_advisories_test.go
- manager/controllers/system_delete.go
- manager/controllers/system_delete_test.go
- manager/controllers/system_detail.go
- manager/controllers/system_detail_test.go
- manager/controllers/system_packages.go
- manager/controllers/system_packages_export.go
- manager/controllers/system_packages_export_test.go
- manager/controllers/system_packages_test.go
> SPM-1061: Manager returns 500 (unknonw system)

- listener/upload.go
Create 2 separate repos `epel-7` and `epel-8` and map the `epel` repo onto them based on OS version.
> SPM-1048: Map EPEL repos based on os version

- base/database/utils.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
> SPM-1055: Improve package-systems endpoint sql query

- vmaas_sync/metrics_cyndi.go
- vmaas_sync/metrics_cyndi_test.go
> SPM-1055: Remove useless tags counts metric

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.8

- base/database/utils.go
- manager/controllers/packages.go
> SPM-1055: Improve /packages sql query

- deploy/clowdapp.yaml
- these services failed before when being deployed with
> SPM-674: Use 'ingress' and 'puptoo' in Clowder config

- deploy/clowdapp.yaml
> SPM-674: Fixed clowdapp db credentials for evaluators and listener

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.12.9

- base/database/utils.go
- base/metrics/metrics.go
- deploy/clowdapp.yaml
- docs/openapi.json
- manager/controllers/packages.go
- manager/manager.go
> stable 1.12.9

- database_admin/migrations/066_package_latest_redefine.up.sql
- database_admin/schema/create_schema.sql
- dev/test_data.sql
- evaluator/package_cache_test.go
- vmaas_sync/metrics_test.go
- vmaas_sync/package_cache_sort_test.go
- vmaas_sync/refresh.go
> SPM-991: Fix latest_package_cache view

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.13.0

- database_admin/migrations/067_unspecified_advisories.down.sql
- database_admin/migrations/067_unspecified_advisories.up.sql
- database_admin/schema/create_schema.sql
- vmaas_sync/advisory_sync.go
> SPM-1047: Add unspecified advisory type, add remapping fron newpackage to enhancement

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.14.0

- base/database/utils.go
- base/metrics/metrics.go
- database_admin/migrations/067_unspecified_advisories.down.sql
- database_admin/migrations/067_unspecified_advisories.up.sql
- database_admin/schema/create_schema.sql
- docs/openapi.json
- manager/controllers/packages.go
- manager/manager.go
- vmaas_sync/advisory_sync.go
> stable 1.14.0

- dev/database/custom.conf
- vmaas_sync/metrics.go
- vmaas_sync/metrics_test.go
> SPM-1076: run only one query for all 8 system metrics

- deploy/clowdapp.yaml
> SPM-1086: Enable Cyndi and iqePlugin in clowder config

- vmaas_sync/metrics.go
- vmaas_sync/metrics_cyndi.go
- vmaas_sync/metrics_cyndi_test.go
> SPM-1081: improve/speedup cyndi and advisory metrics

- vmaas_sync/advisory_sync.go
- vmaas_sync/metrics.go
> SPM-1049: Advisories sync mismatch metric

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.14.1

- base/metrics/metrics.go
- deploy/clowdapp.yaml
- dev/database/custom.conf
- docs/openapi.json
- manager/manager.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/metrics.go
- vmaas_sync/metrics_cyndi.go
- vmaas_sync/metrics_cyndi_test.go
- vmaas_sync/metrics_test.go
> Stable 1.14.1

- evaluator/evaluate_packages.go
- evaluator/package_cache.go
> SPM-1091: Fix system-package items loading in package analysis

- evaluator/evaluate.go
> SPM-1091: Fix advisory type index in evaluate.go

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.14.2

- base/metrics/metrics.go
- docs/openapi.json
- evaluator/evaluate.go
- evaluator/evaluate_packages.go
- evaluator/package_cache.go
- manager/manager.go
> Stable 1.14.2

- database_admin/migrations/068_package_latest_fix.up.sql
- database_admin/schema/create_schema.sql
> SPM-1083: Fix package_latest_cache containing no summary

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.15.0

- base/metrics/metrics.go
- database_admin/migrations/068_package_latest_fix.up.sql
- database_admin/schema/create_schema.sql
- docs/openapi.json
- evaluator/evaluate.go
- manager/manager.go
> Stable 1.15.0

- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/repo_sync.go
> SPM-1089: Fix setting of thid_party flag for repos

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.15.1

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
- vmaas_sync/repo_based.go
- vmaas_sync/repo_based_test.go
- vmaas_sync/repo_sync.go
> stable 1.15.1

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.15.2

- base/metrics/metrics.go
- docs/openapi.json
- evaluator/evaluate.go
- evaluator/evaluate_packages.go
- manager/manager.go
> stable 1.15.2

- listener/common_test.go
- listener/upload.go
- listener/upload_test.go
> Map epel repos for vmaas_json

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> Bump version to 1.15.3

- base/metrics/metrics.go
- docs/openapi.json
- listener/common_test.go
- listener/upload.go
- listener/upload_test.go
- manager/manager.go
> Deploy 1.15.3 to stage

- deploy/clowdapp.yaml
> SPM-1075: Added secrets and params to Clowder config

- dev/test_data.sql
- docs/openapi.json
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/systems.go
- manager/controllers/systems_export.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
> SPM-1111: include other advisory type count

- docs/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/package_systems.go
- manager/controllers/package_versions.go
- manager/controllers/packages.go
- manager/controllers/structures.go
- manager/controllers/system_advisories.go
- manager/controllers/system_packages.go
- manager/controllers/systems.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
> SPM-947 add patched / unpatched counts to API

- pr_check.sh
**Just for testing clowder and learn steps**
> SPM-955: Smoke test with CJI

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.15.4

- base/metrics/metrics.go
- deploy/clowdapp.yaml
- dev/test_data.sql
- docs/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/package_systems.go
- manager/controllers/package_versions.go
- manager/controllers/packages.go
- manager/controllers/structures.go
- manager/controllers/system_advisories.go
- manager/controllers/system_packages.go
- manager/controllers/systems.go
- manager/controllers/systems_export.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
- manager/manager.go
- pr_check.sh
> Stable 1.15.4

- vmaas_sync/repo_sync.go
- vmaas_sync/vmaas_sync.go
> SPM-1117: Force downloading of all repos

- manager/controllers/package_versions.go
- manager/controllers/package_versions_test.go
> SPM-1059: Return 404 for invalid package name

- deploy/clowdapp.yaml
> SPM-1125: Updated cyndi.appName (patchman -> patch) in clowdapp.yaml

- deploy/clowdapp.yaml
> SPM-1125: Fix log level params in clowdapp.yml

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
use "patchman.*-evaluator.." pattern in evaluator pod names to
cover both patchman-engine-evaluator and patchman-evaluator
> SPM-1125: Update grafana config

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> SPM-1125: Update grafana config - single values

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> SPM-1125: Fixed grafana config regex patterns

- evaluator/evaluate.go
> SPM-1087 Add vmass call log

- base/utils/config.go
vmaas "service" fields values changed ("webapp" > "webapp-service") etc.
> SPM-1146: Update vmaas address reading in Clowder

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.15.6

- base/metrics/metrics.go
- base/utils/config.go
- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- deploy/clowdapp.yaml
- docs/openapi.json
- evaluator/evaluate.go
- manager/manager.go
> stable 1.15.6

- deploy/clowdapp.yaml
to allow setting vmaas address when vmaas is not deployed with Clowder
> SPM-1148: Add VMAAS_ADDRESS to clowdapp.yaml

- deploy/clowdapp.yaml
> SPM-1148: Add VMAAS_WS_ADDRESS to clowdapp.yaml

- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/packages_export_test.go
- manager/controllers/system_advisories_export_test.go
- manager/controllers/system_advisories_test.go
- manager/controllers/system_delete_test.go
- manager/controllers/system_detail_test.go
- manager/controllers/system_packages_export_test.go
- manager/controllers/system_packages_test.go
- manager/controllers/systems_advisories_view_test.go
- manager/controllers/systems_auth_test.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
> SPM-1132: Return 400 when using incorrect filter

- listener/upload.go
- listener/upload_test.go
> SPM-1154: Fix nil pointer in fixEpelRepos, listener component

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.15.7

- evaluator/evaluate.go
- evaluator/evaluate_advisories.go
- evaluator/evaluate_packages.go
- listener/upload.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/package_sync.go
- vmaas_sync/repo_based.go
> SPM-1017: Switch to INFO log level

- manager/controllers/package_systems_export.go
- manager/controllers/package_systems_export_test.go
> SPM-1151: return 404 for invalid package name - package systems export

- manager/controllers/package_systems.go
- manager/controllers/package_systems_test.go
> SPM-1150: return 404 for unknown package name - package systems

- base/models/models.go
- database_admin/migrations/069_reboot_required.down.sql
- database_admin/migrations/069_reboot_required.up.sql
- database_admin/schema/create_schema.sql
- docs/openapi.json
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_export_test.go
- manager/controllers/system_advisories_test.go
> SPM-806: Add "reboot_required" info to advisory

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.16.0

- deploy/clowdapp.yaml
> SPM-1159: added liveness, readiness probes to database-admin

- dev/kafka/Dockerfile
- dev/kafka/entrypoint.sh
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
> run test kafka instance directly from git

- docs/openapi.json
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_detail_test.go
> SPM-806: Added "reboot_required" info to advisory detail API

- base/metrics/metrics.go
- docs/openapi.json
- manager/manager.go
> bump version 1.16.1

- base/metrics/metrics.go
- deploy/clowdapp.yaml
- dev/kafka/Dockerfile
- dev/kafka/entrypoint.sh
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
- docs/openapi.json
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_detail_test.go
- manager/manager.go
> stable 1.16.1

- deploy/clowdapp.yaml
> SPM-1165: Add advisory detail cache vars to manager deploy config

- .github/workflows/semantic-release.yml
- scripts/increment_version.sh
> SPM-1169: Added 'semantic release' github action

- manager/controllers/advisories_export_test.go
- manager/controllers/utils.go
> SPM-1132: Export endpoint bad filter response

- base/database/query.go
- base/database/query_test.go
- manager/controllers/filter.go
- manager/controllers/filter_test.go
- manager/controllers/utils.go
> SPM-1185: Implement the order_query reflection attribute

- base/models/models.go
- database_admin/migrations/070_advisory_type_preference.down.sql
- database_admin/migrations/070_advisory_type_preference.up.sql
- database_admin/schema/create_schema.sql
- docs/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_advisories_export_test.go
- manager/controllers/system_advisories_test.go
> SPM-1185: Add "preference" column to "advisory_type" table.

- base/database/query.go
- base/database/query_test.go
- docs/openapi.json
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/systems.go
- manager/controllers/systems_export.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
> SPM-1213: Added system tags to /*systems endpoints

- deploy/clowdapp.yaml
- evaluator/evaluate.go
> SPM-1234: Add vmaas call retry vars

- base/models/models.go
- database_admin/migrations/071_advisory_release_versions.down.sql
- database_admin/migrations/071_advisory_release_versions.up.sql
- database_admin/schema/create_schema.sql
- dev/test_data.sql
- docs/openapi.json
- go.mod
- go.sum
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_detail_test.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/advisory_sync_test.go
> SPM-1166: add errata release_version into /advisories API

- deploy/clowdapp.yaml
- go.mod
- go.sum
- platform/vmaas.go
- vmaas_sync/package_sync.go
- vmaas_sync/package_sync_test.go
- vmaas_sync/vmaas_sync.go
> SPM-889: Use vmaas /pkglist endpoint to sync packages

- docs/openapi.json
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/package_systems_test.go
> SPM-1213: Added tags info to package system endpoint

- manager/controllers/advisory_systems_export.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/package_systems_test.go
- manager/controllers/systems.go
- manager/controllers/systems_export.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
> SPM-1213: Added "tags" field to *systems csv export

- deploy/clowdapp.yaml
- vmaas_sync/advisory_sync.go
- vmaas_sync/package_sync.go
> SPM-889: Added package sync check

- manager/controllers/advisory_detail.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/package_detail.go
- manager/controllers/package_detail_test.go
- manager/controllers/system_detail.go
- manager/controllers/system_detail_test.go
- manager/controllers/utils.go
> SPM-1132: Return 400 when filter is not supported

- database_admin/migrate.sh
- docker-compose.prod.yml
- docker-compose.yml
- scripts/wait-for-sessions-closed.sh
> SPM-1279: Simplify migration process

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- histogram charts replaced with standard charts (easier to understand)
- removed some less interesting charts to keep the board clear
> SPM-1278: Grafana update - replace histogram charts

- docs/openapi.json
- manager/controllers/baselines.go
- manager/controllers/baselines_test.go
- manager/routes/routes.go
@Josca The new Api is returning correct response, but I was not able to generate new OpenApi docs using './scripts/generate_docs.sh'. This command is always giving current docs.
> SPM-1261: new api for baselines read

- docs/openapi.json
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/system_detail_test.go
- manager/controllers/systems.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
- We don't want to show these updates now in API.
> SPM-1259: Temporarily hide baseline API info

- sonar-project.properties
> SPM-1292: sonar-project properties

- docs/openapi.json
- manager/controllers/baseline_systems.go
- manager/controllers/baseline_systems_test.go
- manager/routes/routes.go
> SPM-1261: new endpoints for reading baseline systems

- base/database/baseline.go
- base/database/baseline_test.go
- deploy/clowdapp.yaml
- dev/test_data.sql
- evaluator/evaluate.go
- evaluator/evaluate_advisories.go
- evaluator/evaluate_baseline.go
- evaluator/evaluate_baseline_test.go
> SPM-1260: evaluate baseline

- conf/local.env
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/baseline_systems_test.go
- manager/controllers/baselines_test.go
- manager/controllers/package_detail_test.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/package_systems_test.go
- manager/controllers/package_versions_test.go
- manager/controllers/packages_export_test.go
- manager/controllers/packages_test.go
- manager/controllers/system_advisories_export_test.go
- manager/controllers/system_advisories_test.go
- manager/controllers/system_detail_test.go
- manager/controllers/system_packages_export_test.go
- manager/controllers/system_packages_test.go
- manager/controllers/systems_advisories_view_test.go
- manager/controllers/systems_auth_test.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
- manager/controllers/test_utils.go
- scripts/wait-for-services.sh
> SPM-1259: Some fixes

- base/utils/rpm_test.go
- database_admin/migrations/011_culling_timestamps.up.sql
- database_admin/migrations/052_system_repo.up.sql
- database_admin/migrations/059_system_package_reverse_idx.up.sql
- database_admin/migrations/062_first_reported.down.sql
> SPM-1312: sonarqube fixes

- base/database/testing.go
- database_admin/migrations/073_modify_system_platform_permissions.down.sql
- database_admin/migrations/073_modify_system_platform_permissions.up.sql
- database_admin/schema/create_schema.sql
- docs/openapi.json
- manager/controllers/baseline_update.go
- manager/controllers/baseline_update_test.go
- manager/middlewares/rbac.go
- manager/routes/routes.go
> SPM-1261: Baseline update

- base/database/setup.go
- dev/test_data.sql
- docs/openapi.json
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/filter.go
- manager/controllers/filter_test.go
- manager/controllers/system_advisories.go
- manager/controllers/systems_test.go
- vmaas_sync/metrics.go
- vmaas_sync/metrics_test.go
> SPM-1289: Support filter advisory_type_name[other]

- deploy/clowdapp.yaml
- evaluator/evaluate.go
- when enabled, use "optimistic_updates=true" for all vmaas calls, not only for systems with third party repos
> SPM-1282: Added VMAAS_CALL_USE_OPTIMISTIC_UPDATES to evaluator

- docs/openapi.json
- manager/controllers/baseline_create.go
- manager/controllers/baseline_create_test.go
- manager/controllers/baseline_update.go
- manager/middlewares/rbac.go
- manager/routes/routes.go
> SPM-1261: Create a baseline endpoint

- base/database/testing.go
- docs/openapi.json
- manager/controllers/baseline_delete.go
- manager/controllers/baseline_delete_test.go
- manager/controllers/baseline_update.go
- manager/controllers/baseline_update_test.go
- manager/middlewares/rbac.go
- manager/routes/routes.go
> SPM-1261: Added delete_baseline endpoint

- manager/controllers/systems.go
when major or minor is unknown report just name
when name is unknown report nothing
> SPM-1238: make os version consistent with vulnerability

- base/database/setup.go
- manager/controllers/advisories_test.go
- manager/controllers/filter.go
> SPM-1289: Added log to show "other advisory types"

- Dockerfile
- docs/openapi.json
- manager/controllers/baseline_update.go
- vmaas_sync/vmaas_sync.go
> SPM-1349: Used CentOS 8 Stream in Dockerfile (Centos 8 EOL)

- deploy/clowdapp.yaml
- evaluator/evaluate_test.go
- vmaas_sync/package_sync.go
- vmaas_sync/package_sync_test.go
- vmaas_sync/vmaas_sync.go
> SPM-1349: Removed useless pkg tree option in vmaas_sync

- deploy/clowdapp.yaml
> SPM-1268: Added Floorist (DataHub) config to deploy/clowdapp.yaml

- deploy/clowdapp.yaml
> SPM-1268: Fixed floorist sql query in deploy/clowdapp.yaml

- base/database/testing.go
- docs/openapi.json
- manager/controllers/baseline_detail.go
- manager/controllers/baseline_detail_test.go
- manager/routes/routes.go
> SPM-1261: Added baseline_detail endpoint

- base/database/baseline.go
- docs/openapi.json
- manager/controllers/baseline_create.go
- manager/controllers/baseline_detail.go
- manager/controllers/baseline_systems.go
- manager/controllers/baseline_systems_test.go
- manager/controllers/baseline_update.go
- manager/controllers/baselines.go
- manager/controllers/structures.go
> SPM-1261: Updated structs comments (swag annotations)

- README.md
- docs/openapi.json
- manager/manager.go
> SPM-1372: fix links in the documentation

- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/baseline_systems.go
- manager/controllers/baselines.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
- manager/controllers/package_systems_test.go
- manager/controllers/package_versions.go
- manager/controllers/packages.go
- manager/controllers/packages_export.go
- manager/controllers/packages_test.go
- manager/controllers/system_advisories.go
- manager/controllers/system_packages.go
- manager/controllers/systems.go
- manager/controllers/systems_export.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
> SPM-1315: Add tag and SAP workload filters into metadata

- docker-compose.prod.yml
- docker-compose.yml
> SPM-1382: fix data path in postgresql container

- docs/openapi.json
- manager/controllers/baseline_create.go
- manager/controllers/baseline_create_test.go
- manager/controllers/baseline_delete.go
- manager/controllers/baseline_delete_test.go
- manager/controllers/baseline_detail.go
- manager/controllers/baseline_update.go
- manager/controllers/baseline_update_test.go
> SPM-1261: Fix baseline API responses

- README.md
> SPM-1349: Added deps backup repo link to README.md

- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/test_utils.go
> SPM-1371: Add subtotals metadata to advisories

- base/database/baseline.go
- base/database/baseline_test.go
- evaluator/evaluate_baseline.go
> SPM-1440: Fix GetBaselineConfig method

- scripts/check-openapi-docs.sh
- scripts/generate_docs.sh
> SPM-1398: Simplify swagger doc generator

- docs/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/baseline_create.go
- manager/controllers/baseline_delete.go
- manager/controllers/baseline_detail.go
- manager/controllers/baseline_systems.go
- manager/controllers/baseline_update.go
- manager/controllers/baselines.go
- manager/controllers/package_detail.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
- manager/controllers/package_versions.go
- manager/controllers/packages.go
- manager/controllers/packages_export.go
- manager/controllers/status.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_delete.go
- manager/controllers/system_detail.go
- manager/controllers/system_packages.go
- manager/controllers/system_packages_export.go
- manager/controllers/systems.go
- manager/controllers/systems_advisories_view.go
- manager/controllers/systems_export.go
> SPM-1320: Update non-200 response API types

- docs/openapi.json
- manager/controllers/baseline_create.go
- manager/controllers/baseline_delete.go
- manager/controllers/baseline_update.go
- manager/controllers/baseline_update_test.go
> SPM-1403: Return baseline details on baseline-update

- base/utils/rpm.go
> SPM-1398: Extend nevra parse error log

- docs/openapi.json
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/system_detail_test.go
- manager/controllers/systems.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
> SPM-1414: Added baseline info to existing endpoints

- base/database/testing.go
- base/models/models.go
- database_admin/migrations/075_synced_boolean.down.sql
- database_admin/migrations/075_synced_boolean.up.sql
- database_admin/migrations/076_system_package_pkg_idx.down.sql
- database_admin/migrations/076_system_package_pkg_idx.up.sql
- database_admin/schema/create_schema.sql
- deploy/clowdapp.yaml
- dev/test_data.sql
- dev/test_generate_data.sql
- evaluator/evaluate_packages_test.go
- listener/common_test.go
- vmaas_sync/advisory_sync.go
- vmaas_sync/advisory_sync_test.go
- vmaas_sync/clean_unused_data.go
- vmaas_sync/clean_unused_data_test.go
- vmaas_sync/package_sync.go
- vmaas_sync/package_sync_test.go
- vmaas_sync/vmaas_sync.go
> SPM-1361: clean unused packages

- base/models/models.go
- database_admin/migrations/077_yumupdate_column.down.sql
- database_admin/migrations/077_yumupdate_column.up.sql
- database_admin/schema/create_schema.sql
- listener/common_test.go
- listener/upload.go
- listener/upload_test.go
> SPM-1325: Update listener to read updateinfo from kafka

- manager/controllers/utils.go
> SPM-1392: Fix nil pointer dereference on tags

- manager/controllers/utils.go
- manager/controllers/utils_test.go
> SPM-1411: Fix infinite loop in nestedQuery

- manager/controllers/utils.go
> SPM-1392: key should not start with "/" if namespace is empty

- manager/controllers/baseline_detail.go
> SPM-1416: Remove omitempty from response

- manager/controllers/baselines.go
- manager/controllers/baselines_test.go
> SPM-1442: Sort baselines list by name ascending

- Dockerfile
- base/utils/config.go
- conf/common.env
- deploy/clowdapp.yaml
- dev/scripts/advisories_list.sh
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
- scripts/entrypoint.sh
- scripts/try_export_clowder_params.sh
- vmaas_sync/entrypoint.sh
> SPM-1455: clean unused haberdasher 

- base/database/baseline_test.go
- base/database/testing.go
- base/metrics/metrics.go
- docs/docs_test.go
- docs/openapi.json
- manager/controllers/baseline_delete_test.go
- manager/controllers/baseline_detail_test.go
- manager/controllers/baseline_systems_remove.go
- manager/controllers/baseline_systems_remove_test.go
- manager/controllers/baseline_update_test.go
- manager/routes/routes.go
> SPM-1433: Add endpoint to remove patch sets from system list

- manager/controllers/baseline_create.go
- manager/controllers/baseline_update.go
- manager/controllers/baseline_update_test.go
> SPM-1460: Check if system belongs to baseline during update

- Dockerfile
> SPM-1469: temporarily force go-toolset-1.17 from centos stream

- Dockerfile
- database_admin/migrate.sh
- scripts/entrypoint.sh
- scripts/try_export_clowder_params.sh
build on aarch64 requires building [librdkafka](https://github.com/edenhill/librdkafka) from source and building go app with `go build -tags dynamic` to link shared library with [confluent-kafka-go](https://github.com/confluentinc/confluent-kafka-go) 
> SPM-1469: allow build on aarch64

- database_admin/migrations/079_manager_create_rh_account.down.sql
- database_admin/migrations/079_manager_create_rh_account.up.sql
- database_admin/schema/create_schema.sql
- listener/common_test.go
- listener/upload.go
- listener/upload_test.go
- manager/middlewares/authentication.go
- manager/middlewares/authentication_test.go
- pr_check.sh
> SPM-1459: create rh_account on first request

- docs/openapi.json
- manager/controllers/systems_export.go
- manager/controllers/systems_export_test.go
> SPM-1475: export/system baseline filter

- Dockerfile
RHEL 8.6 with go-toolset-1.17 is out
This reverts commit 5f1dae0d98e90ed82c3e64ee52cf25204ac852c1.
> RHEL 8.6 with  go-toolset-1.17 is out

- Dockerfile
RequestError: send request failed\ncaused by: Post \"https://.../\": x509: certificate signed by unknown authority: unable to setup CloudWatch logging
failed to initialize database, got error failed to connect to `host=patchman-stage...`: failed to write startup message (x509: certificate relies on legacy Common Name field, use SANs instead
> SPM-1505: temporarily switch back to workaround cert issue in stage

- deploy/clowdapp.yaml
go 1.17 no more recognize this option
> SPM-1505: remove unused x509ignoreCN=0

- base/notification/notification.go
- base/utils/config.go
- conf/evaluator_common.env
- conf/test.env
- deploy/clowdapp.yaml
- evaluator/evaluate.go
- evaluator/evaluate_advisories.go
- evaluator/evaluate_advisories_test.go
- evaluator/notifications.go
- evaluator/notifications_test.go
> SPM-1484: Add instant advisory notifications

- listener/events.go
> SPM-1324: let's log whole message when tracing error

- base/base.go
- base/mqueue/event.go
- base/mqueue/mqueue_test.go
- base/mqueue/payload_tracker_event.go
- base/mqueue/platform_event.go
- base/utils/config.go
- conf/evaluator_recalc.env
- conf/evaluator_upload.env
- conf/listener.env
- conf/test.env
- deploy/clowdapp.yaml
- evaluator/evaluate.go
- evaluator/evaluate_test.go
- evaluator/notifications_test.go
- listener/common_test.go
- listener/events_test.go
- listener/listener.go
- listener/upload.go
- listener/upload_test.go
- manager/kafka/kafka.go
- vmaas_sync/send_messages.go
> SPM-1501: add payload tracker and use org_id from kafka messages

- deploy/clowdapp.yaml
Add org_id populator to translate account numbers to org_ids - https://github.com/RedHatInsights/tenant-utils/blob/main/cmd/org-id-column-populator/README.md
> SPM-1550: add org_id populator cji

- base/database/setup.go
- base/database/setup_test.go
- evaluator/evaluate.go
- evaluator/notifications.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_detail.go
> SPM-1546: Read static data from memory instead of DB

- base/database/utils.go
> SPM-1537: handle panic in DBWait

- base/mqueue/platform_event.go
fixes
```
time="2022-06-10T14:47:36Z" level=error msg="Invalid 'delete' message format" fields.msg="{\"insights_id\": \"4dbf09d0-848b-47f1-b60e-420cf0632c18\", \"metadata\": {\"request_id\": \"-1\"}, \"type\": \"delete\", \"account\": \"0369233\", \"timestamp\": \"2022-06-10T14:47:36.984126+00:00\", \"id\": \"13668aff-cc47-4120-bb1b-5e577813ffed\", \"org_id\": \"3340851\", \"request_id\": \"-1\"}" inventoryID=13668aff-cc47-4120-bb1b-5e577813ffed
```
`RequestIDs` have to be marshalled/unmarshalled as `request_ids`, not `request_id`
> SPM-1563: fix unmarshaling of delete msg

- dev/kafka/entrypoint.sh
- dev/kafka/setup.sh
- dev/scripts/epemeral-port-forward.sh
- scripts/colorize.sh
> devel setup improvements

- base/mqueue/platform_event.go
- base/notification/notification.go
- evaluator/evaluate.go
- evaluator/notifications.go
- evaluator/notifications_test.go
> SPM-1484: Use RH account name instead of ID

- evaluator/evaluate.go
> move check for empty json to correct function

- base/mqueue/mqueue_impl_gokafka.go
> SPM-1594: use LeastBytes kafka balancer

- deploy/clowdapp.yaml
> Lower batch-size and increase timeout for org-id-populator

- listener/metrics.go
- listener/upload.go
add more metrics to debug where listener spends most time
> SPM-1600: add listener part duration metrics

- base/mqueue/payload_tracker_event.go
- evaluator/evaluate.go
@MichaelMraka what do you think?
> Minor refactoring

- database_admin/migrate.go
- database_admin/update.go
- deploy/clowdapp.yaml
> SPM-1601: fix failed schema_migration

- listener/metrics.go
> SPM-1600: register messagePartDuration

- deploy/clowdapp.yaml
it is not needed anymore, we've translated all accounts in production
> SPM-1550: remove org-id-populator

- evaluator/notifications.go
> SPM-1484: Add notif info log on success

- docs/v1/openapi.json
- docs/v2/openapi.json
- manager/controllers/advisory_detail.go
needed for iqe tests to generate client with same methods as before
> Rename operationId for advisory detail endpoint

- base/mqueue/payload_tracker_event.go
- deploy/clowdapp.yaml
- evaluator/evaluate.go
Add ability to stop these functionalities if we see that performance in prod decreased due to these features
> Feature flags for notifications and payload tracker

- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/package_cache_test.go
- vmaas_sync/metrics_test.go
> SPM-1609: lazy save unknown packages

- README.md
> Readme fix: running single test

- manager/controllers/advisory_detail.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/utils.go
- vmaas_sync/advisory_sync_test.go
> SPM-1619: fix advisory_detail with old data in db

- manager/controllers/advisory_detail_test.go
> SPM-1619: packages from map can be in random order

- manager/controllers/baseline_systems_remove.go
- manager/controllers/baseline_systems_remove_test.go
> SPM-1576: fix 500 in BaselineSystemsRemove

- manager/controllers/advisory_detail.go
> Store all pkg names in advisory detail v1 api

- deploy/clowdapp.yaml
> add apiPath to clowdapp

- base/mqueue/platform_event.go
- base/notification/notification.go
- evaluator/evaluate.go
- evaluator/notifications.go
- evaluator/notifications_test.go
> SPM-1626: Include OrgID in notification messages

- database_admin/migrations/084_evaluator_insert_package_name.down.sql
- database_admin/migrations/084_evaluator_insert_package_name.up.sql
- database_admin/schema/create_schema.sql
> SPM-1633: grant package_name permissions for evaluator

- deploy/clowdapp.yaml
> SPM-1636: split limit and request values

- base/database/testing.go
- base/utils/openapi.go
- manager/controllers/baseline_create.go
- manager/controllers/baseline_create_test.go
- manager/controllers/baseline_update_test.go
> SPM-1630: fix baseline creation 500

- database_admin/migrations/081_empty_strings.up.sql
> SPM-1648: Fix migration 81 deadlock

- base/mqueue/platform_event.go
- base/notification/notification.go
- evaluator/evaluate.go
- evaluator/notifications.go
- evaluator/notifications_test.go
Eventing requested adding more context to notification message, so they can use that in their tools.
> SPM-1649: Add more context to notification message

- base/utils/vmaas.go
- base/utils/vmaas_inputs_test.go
- base/utils/vmaas_test.go
- evaluator/evaluate.go
PR should fix the issue with missing up-to-date packages when yum_updates are evaluated, currently only upgradable packages are shown
> SPM-1655: store up-to-date systems

- base/utils/vmaas.go
- evaluator/evaluate.go
- listener/common_test.go
- listener/upload.go
- listener/upload_test.go
> SPM-1676: filter older pkgs in yum_updates

- base/utils/vmaas.go
> SPM-1676: fix RemoveNonLatestPackages

- dev/scripts/advisories_list.sh
- dev/scripts/advisory_detail.sh
- dev/scripts/ephemeral-port-forward.sh
- dev/scripts/metrics.sh
- dev/scripts/platform_vmaas_updates.sh
- dev/scripts/system_detail.sh
- dev/scripts/systems_applicable.sh
- dev/scripts/systems_list.sh
- docker-compose.prod.yml
- docker-compose.yml
- listener/upload.go
- listener/upload_test.go
- platform/platform.go
> small fixes and developer setup improvements

- .github/workflows/open_api_spec.yml
> updated openapi-generator image to the latest stable / supported

- base/utils/rpm.go
- base/utils/rpm_test.go
> SPM-1692: parse pkg with empty version, release, arch

- evaluator/evaluate.go
> SPM-1694: call vmaas even with yum_updates

- docs/v2/openapi.json
- manager/controllers/structures.go
- manager/controllers/utils.go
add `has_systems` to metadata to indicate whether user has some systems registered
> SPM-1696: add has_systems meta

- dev/kafka/Dockerfile
- dev/kafka/setup.sh
- docker-compose.prod.yml
- docker-compose.yml
use kafka 7.0.5 in docker-compose
> Update local kafka

- main.go
- tasks/caches/caches.go
- tasks/cleaning/clean_unused_data.go
> SPM-1617: fix main for jobs and add logs

- docker-compose.test.yml
> Update zookeeper in docker-compose.test

- base/mqueue/payload_tracker_event.go
- base/mqueue/platform_event.go
- base/notification/notification.go
- base/utils/identity.go
- evaluator/evaluate.go
- listener/common_test.go
- listener/upload.go
- listener/upload_test.go
- manager/middlewares/authentication.go
- manager/middlewares/authentication_test.go
> SPM-1695: remove account_number usage

- base/mqueue/platform_event.go
- tasks/vmaas_sync/repo_based.go
- tasks/vmaas_sync/repo_based_test.go
- tasks/vmaas_sync/send_messages.go
> SPM-1705: Add OrgID to eval recalc messages (no refactor)

- .github/workflows/semantic-release.yml
> let semantic-release also update default image in clowder template

- .github/workflows/semantic-release.yml
> push both commits to trigger image build

- .github/workflows/semantic-release.yml
> delay second commit to get jenkins chance process both of them

- .github/workflows/semantic-release.yml
- build_deploy.sh
> tag images with version

- database_admin/update.go
> SPM-1700: don't block with latest schema

- dev/kafka/entrypoint.sh
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
> try to fix NodeExistsException on kafka start

- Dockerfile
these are the most frequently changed files
```
✗ git log --pretty=format: --name-only | sort | uniq -c | sort -rg | head -20
1781
266 manager/manager.go
265 docs/openapi.json
248 base/metrics/metrics.go
177 evaluator/evaluate.go
128 listener/upload.go
88 database_admin/schema/create_schema.sql
87 manager/controllers/systems.go
82 docs/v2/openapi.json
77 go.mod
75 manager/controllers/utils.go
75 dev/test_data.sql
74 manager/controllers/advisories.go
71 vmaas_sync/advisory_sync.go
71 manager/controllers/systems_test.go
71 go.sum
69 evaluator/evaluate_test.go
68 docker-compose.yml
68 base/models/models.go
66 listener/upload_test.go
```
> reorder add statements in dockerfile for better caching

- dev/scripts/send-kafka-msg.go
- platform/platform.go
> SPM-1560: Script for sending custom kafka messages

- dev/test_data.sql
- tasks/vmaas_sync/package_sync.go
- tasks/vmaas_sync/package_sync_test.go
> SPM-1706: rewrite upserts in package_sync

- database_admin/migrations/088_update_package_name_summary.up.sql
- database_admin/schema/create_schema.sql
> SPM-1605: update package_name summary after schema change

- base/utils/rpm.go
- base/utils/rpm_test.go
> SPM-1713: fix wrong rpm comparison

- base/database/testing.go
- base/mqueue/platform_event.go
- base/mqueue/platform_event_test.go
- manager/kafka/kafka.go
- tasks/vmaas_sync/repo_based.go
- tasks/vmaas_sync/repo_based_test.go
- tasks/vmaas_sync/send_messages.go
> SPM-1705: Refactor vmaas-sync recalc event

- deploy/clowdapp.yaml
> SPM-1711: use FloorPlan CR

- tasks/vmaas_sync/advisory_sync.go
> SPM-1706: rewrite advisory_metadata upsert

- listener/upload.go
- listener/upload_test.go
> SPM-1706: rewrite system_platform upsert

- listener/upload.go
> SPM-1706: rewrite repo upsert

- listener/upload.go
> SPM-1647: fix repo id type

- base/utils/config.go
- deploy/clowdapp.yaml
- tasks/system_culling/culling.go
- tasks/system_culling/metrics.go
- tasks/vmaas_sync/metrics.go
- tasks/vmaas_sync/vmaas_sync.go
for collecting metrics from jobs we need to use pushgateway, not sure how to test it locally or in ephemeral
> SPM-1712: use pushgateway for metrics from jobs

- deploy/clowdapp.yaml
> add missing pushgateway parameter

- base/database/database.go
- tasks/vmaas_sync/advisory_sync.go
- First one is always true
- Second one is never nil
> Minor logic improvements

- base/notification/notification.go
> SPM-1724: Remove accountID key from notification message

- base/core/config.go
- base/database/setup.go
- docs/v2/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_test.go
- manager/controllers/structures.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_test.go
- manager/controllers/systems.go
- manager/controllers/systems_ids_test.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
- manager/routes/routes.go
add /ids endpoints returning only advisory/system ids
TODO:
> SPM-1690: add /ids endpoints

- base/utils/config.go
> SPM-1725: ignore empty kafka cert

- tasks/vmaas_sync/advisory_sync.go
- tasks/vmaas_sync/advisory_sync_test.go
```
"ERROR: duplicate key value violates unique constraint \"advisory_metadata_pkey\" (SQLSTATE 23505); invalid transaction; 
```
> fix update in advisory sync

- base/core/config.go
- base/utils/gin.go
- docs/v2/openapi.json
- manager/controllers/systems_advisories_view.go
- manager/controllers/systems_advisories_view_test.go
- manager/controllers/utils.go
- added limit,offset to request body
- added Paginate function consistent with pagination in ListCommon
- TODO: unit tests
> SPM-1707: add pagination for views apis

- manager/middlewares/authentication.go
- manager/middlewares/prometheus.go
- manager/routes/routes.go
> SPM-1565: Metric for UI/API caller source

- base/mqueue/mqueue_impl_gokafka.go
> cmp sasl mechanism as lowercase

- docs/v2/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisory_systems.go
- manager/controllers/package_systems.go
- manager/controllers/system_advisories.go
- manager/controllers/systems.go
> SPM-1690: fix openapi spec

- manager/controllers/advisory_systems.go
- manager/controllers/package_systems.go
- manager/controllers/system_advisories.go
- manager/middlewares/authentication.go
can't use errors.Wrap on err=nil 🤦 
> SPM-1730: fix wrong usage of errors.Wrap

- base/api/client.go
- base/types/timestamp.go
- base/vmaas/vmaas.go
- platform/vmaas.go
- tasks/vmaas_sync/dbchange.go
> SPM-1728: fix getting dbchange info

- evaluator/notifications.go
- evaluator/notifications_test.go
> SPM-1732: Sort advisory notification payload by errata name

- manager/controllers/systems_advisories_view.go
- manager/controllers/utils.go
> SPM-1707: fix pagination on views endpoints

- dev/kafka/Dockerfile
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
> SPM-1746: use full container image names

- database_admin/migrations/097_package_cache_inventory_hosts.down.sql
- database_admin/migrations/097_package_cache_inventory_hosts.up.sql
- database_admin/schema/create_schema.sql
- dev/create_inventory_hosts.sql
- dev/test_data.sql
- manager/controllers/packages.go
- scripts/feed_db.go
- scripts/go_test_db.sh
- don't use cache if it is invalid
- join inventory.hosts for consistency
> SPM-1745: Cache consistency

- docs/admin/openapi.json
- turnpike/controllers/admin.go
> SPM-1661: path param in admin spec

- database_admin/migrate.go
> fix forcing migration version

- manager/controllers/systemtags.go
- manager/controllers/systemtags_test.go
> SPM-1737: fix: total tag items count

- base/utils/config.go
- deploy/clowdapp.yaml
- docker-compose.prod.yml
- docker-compose.yml
- docs/admin/openapi.json
- manager/routes/routes.go
- turnpike/controllers/admin.go
> api to list and terminate db sessions

- base/mqueue/mqueue_impl_gokafka.go
```
Unknown sasl type 'scram-sha-512', options: {scram, plain}
```
> SPM-1773: add scram-sha-512 and scram-sha-256 mechanisms

- Dockerfile
- dev/kafka/entrypoint.sh
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
> SPM-1775: let kafka wait for zookeeper

- docs/v2/openapi.json
- manager/controllers/systems_advisories_view.go
- manager/controllers/utils.go
before 
```json
POST "http://localhost:8080/api/patch/v2/views/systems/advisories" -d '{"advisories": ["RH-2"], "limit": 10, "offset": 0}'
{
"data": {
"00000000-0000-0000-0000-000000000001": [
"RH-2"
],
"00000000-0000-0000-0000-000000000003": [
"RH-2"
]
}
}
```
after
```json
POST "http://localhost:8080/api/patch/v2/views/systems/advisories" -d '{"advisories": ["RH-2"], "limit": 10, "offset": 0}'
{
"data": {
"00000000-0000-0000-0000-000000000001": [
"RH-2"
],
"00000000-0000-0000-0000-000000000003": [
"RH-2"
],
"00000000-0000-0000-0000-000000000004": [
""
],
"00000000-0000-0000-0000-000000000005": [
""
],
"00000000-0000-0000-0000-000000000006": [
""
],
"00000000-0000-0000-0000-000000000008": [
""
]
},
"meta": {
"limit": 10,
"offset": 0,
"filter": null,
"total_items": 6
}
} 
```
- …
> SPM-1778: meta and left join for /views

- Dockerfile
> SPM-1782: added forgotten VERSION file to image

- build_deploy.sh
> not enough space in build_master jenkins

- manager/middlewares/logger.go
> SPM-1564: Metrics for request duration

- tasks/vmaas_sync/advisory_sync_test.go
- tasks/vmaas_sync/package_sync_test.go
- tasks/vmaas_sync/repo_based_test.go
- tasks/vmaas_sync/vmaas_sync.go
- tasks/vmaas_sync/vmaas_sync_test.go
- turnpike/controllers/admin.go
> SPM-1796: configure vmaas_sync triggered from admin api

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> SPM-1712: fixed unescaped quotes

- tasks/caches/refresh_packages_caches.go
> package refresh per account

- deploy/clowdapp.yaml
fixing
error: failed to read input object (not a Template?): resource mapping not found
> let new oc handle templates properly

- .golangci.yml
- Dockerfile
- deploy/clowdapp.yaml
- evaluator/evaluate.go
- evaluator/vmaas_cache.go
- scripts/check-deploy-envs.sh
- scripts/go_test_on_ci.sh
- tasks/vmaas_sync/vmaas_sync.go
- tasks/vmaas_sync/vmaas_sync_test.go
> SPM-1738 : cache vmaas call results

- manager/middlewares/logger.go
> SPM-1821: fix request durations metrics

- manager/controllers/systems_advisories_view.go
- systems with no advisories in DB (no record in system_advisories table) should be included in response
- return empty list instead of list containing empty string [""]
> SPM-1828: fix response of views apis

- manager/controllers/advisories_export.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/package_systems_export.go
- manager/controllers/packages_export.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_packages_export.go
- manager/controllers/systems_export.go
- manager/controllers/utils.go
> SPM-1841: merge repeating code in /export APIs

- deploy/clowdapp.yaml
affects ephemeral
```
patchman-admin-mzw2x                        env-ephemeral-x9qw1o-xquihayy.apps.c-rh-c-eph.8p0c.p1.openshiftapps.com        /api/patch/                       patchman-admin                        auth       edge/Redirect   None
patchman-manager-hqcz8                      HostAlreadyClaimed                                                             /api/patch/                       patchman-manager                      auth       edge/Redirect   None
```
> fix duplicated apiPath

- database_admin/migrations/099_hash_partition_id.down.sql
- database_admin/migrations/099_hash_partition_id.up.sql
- database_admin/schema/create_schema.sql
- tasks/caches/refresh_packages_caches.go
> SPM-1848: improve packace cache computation

- base/api/client.go
- base/database/utils.go
- base/mqueue/mqueue_impl_gokafka.go
- base/utils/config.go
- base/vmaas/vmaas.go
- conf/cdappconfig.json
- database_admin/migrate.go
- database_admin/update.go
- deploy/clowdapp.yaml
- dev/scripts/send-kafka-msg.go
- docs/docs.go
- docs/docs_test.go
- scripts/feed_db.go
- use vmaas-go by setting USE_VMAAS_GO env var for evaluator
- sort AvailableUpdates because sorted values are needed for merging with yum_updates
> SPM-1856: ability to run against vmaas-go

- base/utils/vmaas.go
> SPM-1861: when vmaas call fails mergedList is nil

- database_admin/update.go
> SPM-1863: fail hard after some time

- deploy/clowdapp.yaml
> fix job schedule

- tasks/caches/refresh_packages_caches.go
> fix missing quotes (typo)

- base/database/baseline_test.go
- base/database/testing.go
- base/utils/gin.go
- manager/controllers/baseline_create.go
- manager/controllers/baseline_create_test.go
- manager/controllers/baseline_delete_test.go
- manager/controllers/baseline_detail_test.go
- manager/controllers/baseline_systems_remove_test.go
- manager/controllers/baseline_update.go
- manager/controllers/baseline_update_test.go
- empty description should be stored as NULL in DB
- 400 for strings containing only whitespaces 
> SPM-1868: fix baselines 500 with empty description or with whitespaces

- dev/test_generate_data.sql
- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/advisory_systems.go
- manager/controllers/baseline_systems.go
- manager/controllers/baselines.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
- manager/controllers/package_versions.go
- manager/controllers/packages.go
- manager/controllers/packages_export.go
- manager/controllers/system_advisories.go
- manager/controllers/system_packages.go
- manager/controllers/system_packages_test.go
- manager/controllers/systems.go
- manager/controllers/systemtags.go
- manager/controllers/utils.go
> SPM-1871: remove separate query for total items

- deploy/clowdapp.yaml
> don't refresh package cache during upload peak

- base/database/batch.go
- base/database/testing.go
- evaluator/evaluate.go
- evaluator/evaluate_advisories.go
- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/remediations.go
- listener/listener.go
- manager/controllers/baseline_create.go
- manager/kafka/kafka.go
- tasks/vmaas_sync/advisory_sync.go
- tasks/vmaas_sync/metrics_db_test.go
- tasks/vmaas_sync/package_sync.go
> make map allocation consistent in the app

- .github/workflows/semantic-release.yml
- Dockerfile
- base/core/gintesting.go
- docs/docs.go
- docs/v3/openapi.json
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/common_test.go
- manager/manager.go
- manager/middlewares/swagger.go
- manager/routes/routes.go
- scripts/check-openapi-docs.sh
- scripts/generate_docs.sh
> SPM-1910: create v3 API

- manager/middlewares/swagger.go
> fix apiver regex

- base/models/models.go
- database_admin/migrations/101_baseline_timestamps.down.sql
- database_admin/migrations/101_baseline_timestamps.up.sql
- database_admin/schema/create_schema.sql
- docs/v3/openapi.json
- manager/controllers/baseline_create.go
- manager/controllers/baseline_detail.go
- manager/controllers/baseline_update.go
- manager/controllers/baselines.go
- manager/controllers/baselines_test.go
- manager/controllers/utils.go
- manager/middlewares/authentication.go
> SPM-1898: store and return last_edited,published,creator for baseline

- base/models/models.go
- database_admin/migrations/102_systems_status_divergent.down.sql
- database_admin/migrations/102_systems_status_divergent.up.sql
- database_admin/schema/create_schema.sql
- manager/controllers/advisories.go
> SPM-1751: remove unused systems_status_divergent

- docs/v3/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/advisory_systems_v3.go
- manager/controllers/baseline_systems.go
- manager/controllers/baselines.go
- manager/controllers/common_attributes.go
- manager/controllers/package_systems.go
- manager/controllers/package_versions.go
- manager/controllers/packages.go
- manager/controllers/system_advisories.go
- manager/controllers/system_packages.go
- manager/controllers/systems.go
- manager/controllers/systems_export.go
- manager/controllers/systemtags.go
- manager/controllers/utils.go
> SPM-1914: add v3 advisory/systems api

- base/database/testing.go
- base/vmaas/vmaas.go
- database_admin/migrations/104_applicable_advisories.down.sql
- database_admin/migrations/104_applicable_advisories.up.sql
- database_admin/schema/create_schema.sql
- evaluator/evaluate_advisories.go
- evaluator/evaluate_advisories_test.go
- evaluator/evaluate_baseline.go
- evaluator/evaluate_baseline_test.go
- evaluator/remediations.go
- manager/controllers/advisories.go
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- tasks/caches/refresh_advisory_caches_test.go
- tasks/system_culling/system_culling_test.go
> SPM-1751: split advisories into installable/available

- docs/v3/openapi.json
- manager/controllers/baselines.go
> SPM-1931: provide creators meta in /baselines

- base/database/batch.go
- evaluator/evaluate_packages.go
> SPM-1957: hotfix: fixing Storing system packages: extended protocol limited to 65535

- base/database/batch.go
fixing ERROR: there is no parameter $1 (SQLSTATE 42P02)
> SPM-1957: don't Exec empty insert

- Dockerfile
> SPM-1961: ensure image works in fips mode

- docs/v3/openapi.json
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/common_attributes.go
- manager/controllers/system_detail.go
- manager/controllers/systems.go
- manager/controllers/systems_auth_test.go
- manager/controllers/systems_export.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
- manager/controllers/utils.go
> SPM-1913: add /systems v3 api

- docs/v3/openapi.json
- manager/controllers/common_attributes.go
- manager/controllers/system_detail.go
- manager/controllers/system_detail_test.go
depends on https://github.com/RedHatInsights/patchman-engine/pull/1187, need to rebase once https://github.com/RedHatInsights/patchman-engine/pull/1187 is merged
> SPM-1939, SPM-1967 - add baseline_id and fix tags in system_detail

- evaluator/metrics.go
- evaluator/package_cache.go
- evaluator/vmaas_cache.go
- manager/controllers/advisory_detail.go
- manager/middlewares/prometheus.go
> SPM-1813: lru cache utilization metrics

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> SPM-1813: grafana graphs for cache utilization

- base/core/gintesting.go
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/system_detail_test.go
- manager/controllers/systems_auth_test.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
> run tests against v3 api by default

- manager/controllers/utils.go
such query returned 500 `http://localhost:8080/api/patch/v3/systems?filter%5Bstale%5D=True&filter%5Bsystem_profile%5D%5Bsap_sids%5D%5Bin%5D=insights-client%2Fdemo%3D%22%7B%7B%20slug%20%7D%7D%22`
> SPM-1962: fix 500 for filter

- base/utils/config.go
- deploy/clowdapp.yaml
- go.mod
- go.sum
> Uses TLS for Endpoints from Clowder is set

- base/database/setup.go
- base/database/utils.go
- base/utils/config.go
- deploy/clowdapp.yaml
- manager/middlewares/db.go
> SPM-1983: use read replica in manager for GET APIs

- manager/controllers/baseline_systems.go
- manager/controllers/baselines.go
> SPM-1985: show stale systems on baselines

- manager/controllers/utils.go
> SPM-1989: show correct sort in meta

- deploy/clowdapp.yaml
- evaluator/evaluate_advisories.go
- evaluator/evaluate_baseline.go
applicable and installable advisories were not calculated and updated correctly after baseline creation
> SPM-1991: fix baseline system evaluation

- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/common_attributes.go
> SPM-2002: fix advisorySystems status sort

- tasks/caches/refresh_advisory_caches.go
> SPM-2013: process accounts from the same system_account partition together

- database_admin/migrations/108_add_rhsm-system-profile-bridge.up.sql
- database_admin/schema/create_schema.sql
- listener/listener_test.go
> SPM-1816: add new rhsm reporter

- manager/middlewares/authentication.go
- manager/routes/routes.go
> SPM-2024: remove smart management check

- evaluator/vmaas_cache.go
- manager/controllers/advisory_detail.go
- manager/manager.go
- manager/routes/routes.go
> fix cache issues

- build_deploy.sh
> Adding conditional for security compliance branch

- docs/v3/openapi.json
- manager/controllers/systems_advisories_view.go
- manager/controllers/systems_advisories_view_test.go
> SPM-2071: only installable advisories in v3 /views

- docs/v3/openapi.json
- manager/controllers/advisories_export_test.go
- manager/controllers/baseline_systems.go
- manager/controllers/baseline_systems_export.go
- manager/controllers/baseline_systems_export_test.go
- manager/controllers/systems_export_test.go
- manager/controllers/test_utils.go
- manager/controllers/utils.go
> SPM-2077: export baseline systems

- manager/routes/routes.go
> SPM-2077: add route for baseline systems export handler

- docs/v3/openapi.json
- manager/controllers/advisories.go
> SPM-2079: fix invalid sort/filter options in Advisories spec

- deploy/clowdapp.yaml
slow garbage collection causes evaluator restarts
> lower garbage collection limit for evaluators

- docs/v3/openapi.json
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/advisory_systems_v3.go
- manager/controllers/structures.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_test.go
- manager/controllers/utils.go
> SPM-2080: include status in system-advisory /ids

- go.mod
to take advantage of better memory management
> use go 1.19

- base/database/utils.go
- base/models/models.go
- database_admin/migrations/109_update_status.down.sql
- database_admin/migrations/109_update_status.up.sql
- database_admin/schema/create_schema.sql
- dev/test_data.sql
- docs/v3/openapi.json
- evaluator/evaluate.go
- evaluator/evaluate_advisories.go
- evaluator/evaluate_packages.go
- evaluator/status.go
- evaluator/status_test.go
- manager/controllers/system_packages.go
- manager/controllers/system_packages_export.go
- manager/controllers/system_packages_export_test.go
- manager/controllers/system_packages_test.go
> SPM-1915: Update /system/packages API to templates

- deploy/clowdapp.yaml
> use vmaas-go in vmaas-sync

- docs/v3/openapi.json
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/package_systems_test.go
> SPM-1917: update /package/systems

- base/models/models.go
- database_admin/migrations/110_package_account_data_applicable.up.sql
- database_admin/migrations/110_package_account_data_installable.down.sql
- database_admin/schema/create_schema.sql
- deploy/clowdapp.yaml
- docs/v3/openapi.json
- manager/controllers/packages.go
- manager/controllers/packages_export.go
- manager/controllers/packages_export_test.go
- manager/controllers/packages_test.go
- tasks/caches/refresh_packages_caches.go
> SPM-1916: update /packages for templates

- manager/controllers/packages.go
v2 api still needs `systems_updatable` sort and filter, it can be used also for v3 api but it will not be documented
> SPM-1916: backward compatibility for systems_updatable sort and filter

- base/utils/config.go
- base/utils/http.go
- conf/cdappconfig.json
- conf/common.env
- deploy/clowdapp.yaml
- docker-compose.prod.yml
- docker-compose.yml
- docs/admin/openapi.json
- evaluator/evaluate.go
- listener/listener.go
- manager/manager.go
- manager/routes/routes.go
- turnpike/controllers/admin.go
Usage:
- local development in docker-compose
- `go tool pprof http://localhost:{9000|9002|9003|9004}/debug/pprof/{heap|profile|block|mutex}`
- `curl -o trace.out http://localhost:{9000|9002|9003|9004}/debug/pprof/trace?seconds=5 && go tool trace trace.out`
- admin (turnpike) api
- `/api/patch/admin/pprof/{manager|listener|evaluator_upload|evaluator_recalc}/{heap|profile|block|mutex|trace}`
- `go tool pprof <saved.file>`
- `go tool trace <saved.file>`
> add ability to profile code with pprof

- base/models/models.go
- evaluator/evaluate.go
> SPM-2090: improve logging in evaluator

- listener/upload.go
> SPM-2094: lock appending/flushing buffer

- deploy/clowdapp.yaml
> skip rhsm-conduit hosts

- turnpike/controllers/admin.go
> parse query parameters in pprof

- base/database/dbtest.go
- base/models/models.go
- evaluator/evaluate_packages.go
> use system_platform primary key for update

- database_admin/migrations/111_immutable.down.sql
- database_admin/migrations/111_immutable.up.sql
- database_admin/schema/create_schema.sql
> SPM-2093: mark functions as immutable

- tasks/caches/refresh_packages_caches.go
- tasks/common.go
> Read replica and unnest for package refresh job

- deploy/clowdapp.yaml
- tasks/caches/caches.go
- tasks/caches/metrics.go
- tasks/caches/refresh_packages_caches.go
> SPM-2126: add metrics for package_refresh job

- evaluator/evaluate.go
> SPM-2133: log uploadEvaluationDelay hosts

- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> SPM-2126: add grafana graph for package refresh metrics

- evaluator/evaluate.go
There are spikes in grafana but I don't see any logs, let's try to include duration of db update
> log long evaluating systems including db udpate

- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/packages.go
> ESSNTL-4817: don't use cache with inventory groups

- docs/v3/openapi.json
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_v3.go
- manager/controllers/baseline_systems.go
- manager/controllers/baseline_systems_export_test.go
- manager/controllers/common_attributes.go
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/structures.go
- manager/controllers/system_detail.go
- manager/controllers/systems.go
- manager/controllers/systems_export_test.go
- manager/controllers/utils.go
> ESSNTL-4817: add groups to response

- base/models/models.go
- database_admin/migrations/112_advisory_cache_valid.down.sql
- database_admin/migrations/112_advisory_cache_valid.up.sql
- database_admin/schema/create_schema.sql
- evaluator/evaluate.go
- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- tasks/caches/refresh_advisory_caches.go
- tasks/caches/refresh_packages_caches.go
> SPM-2101: run advisory refresh only for accounts with invalid cache

- base/database/utils.go
- base/database/utils_test.go
> ESSNTL-4817: fix ungrouped hosts

- dev/scripts/advisories_list.sh
- dev/scripts/identity.sh
- dev/scripts/systems_list.sh
> update default org in dev scripts

- base/utils/vmaas.go
- docs/v3/openapi.json
- evaluator/evaluate.go
- manager/controllers/system_detail.go
- manager/routes/routes.go
> RHINENG-1198: endpoints to show vmaas_json and yum_updates

- docs/v3/openapi.json
- manager/controllers/system_packages.go
> SPM-2149: add update_status filter to docs

- base/models/models.go
- dev/scripts/advisory_systems.sh
- dev/scripts/kafka-send-message.sh
- dev/scripts/system_packages.sh
- dev/test_data.sql
- docs/v3/openapi.json
- manager/controllers/system_packages.go
- manager/controllers/system_packages_export.go
- manager/controllers/system_packages_export_test.go
> RHINENG-1363: return only latest installable / applicable version of the package

- base/utils/config.go
- deploy/clowdapp.yaml
- manager/controllers/packages.go
- manager/controllers/packages_export.go
- tasks/caches/refresh_packages_caches.go
> SPM-2134: use work_mem for packages queries

- manager/controllers/packages.go
- manager/controllers/packages_export.go
- tasks/caches/refresh_packages_caches.go
- tasks/caches/refresh_packages_caches_test.go
> SPM-2163: fix syntax error while setting work_mem

- manager/controllers/system_advisories.go
> SPM-2167: fix filters in system_advisories

- base/utils/http.go
> RHINENG-1488: return error in http client for non 2xx status code

- manager/controllers/system_packages.go
- manager/controllers/system_packages_test.go
> RHINENG-1495: fix system_packages filters

- manager/controllers/advisories_export.go
- manager/controllers/advisories_export_test.go
> RHINENG-1496: fix advisories_export filter opts

- conf/platform.env
- docker-compose.test.yml
- platform/platform.go
> fix platform_upload

- base/inventory/inventory.go
- base/models/models.go
- database_admin/migrations/113_satellite_managed.down.sql
- database_admin/migrations/113_satellite_managed.up.sql
- database_admin/schema/create_schema.sql
- listener/upload.go
- listener/upload_test.go
> SPM-2103: store satellite_managed flag to db

- base/models/models.go
- base/vmaas/vmaas.go
- database_admin/migrations/114_built_pkgcache.down.sql
- database_admin/migrations/114_built_pkgcache.up.sql
- database_admin/schema/create_schema.sql
- docs/v3/openapi.json
- listener/common_test.go
- listener/upload.go
- listener/upload_test.go
- platform/platform.go
- Past tense of `build_pkgcache` sounds better to me in db, so I named it `built_pkgcache`
> SPM-2105: store in DB if system was uploaded with cache refreshed

- base/vmaas/vmaas.go
depends on https://github.com/RedHatInsights/vmaas-lib/pull/43
> RHINENG-1536: rely on sorted availableUpdates from vmaas

- manager/middlewares/rbac.go
- manager/middlewares/rbac_test.go
> ESSNTL-4817: inventory permission

- evaluator/evaluate.go
- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/utils.go
> RHINENG-1602: fixes for issues found in production during outage

- base/utils/vmaas.go
- base/utils/vmaas_test.go
- base/vmaas/vmaas.go
- evaluator/evaluate.go
- evaluator/evaluate_advisories_test.go
- evaluator/evaluate_baseline.go
- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/evaluate_test.go
- evaluator/remediations_test.go
- listener/upload.go
> RHINENG-1502: evaluate advisories for satellite systems

- manager/controllers/system_packages.go
- manager/controllers/system_packages_export.go
original query - `(cost=243.58..2128.00 rows=684 width=231) (actual time=27.508..32.832 rows=888 loops=1)`
```sql
SELECT
pn.name as name,
p.evra as evra,
sum.value as summary,
descr.value as description,
(update_status(spkg.update_data) = 'Installable') as updatable,
update_status(spkg.update_data) as update_status,
spkg.update_data as updates,
count(*) over () as total
FROM
system_platform sp
JOIN inventory.hosts ih ON ih.id = sp.inventory_id
JOIN system_package spkg on spkg.system_id = sp.id
AND spkg.rh_account_id = 37
JOIN package p on p.id = spkg.package_id
JOIN package_name pn on pn.id = spkg.name_id
LEFT JOIN strings AS descr ON p.description_hash = descr.id
LEFT JOIN strings AS sum ON p.summary_hash = sum.id
WHERE
sp.rh_account_id = 37
AND sp.inventory_id = …
```
> POC: use system_package2 in system_packages

- base/database/utils_test.go
- base/rbac/rbac.go
- manager/middlewares/rbac.go
- manager/middlewares/rbac_test.go
wait for QE investigation what is expected behavior
> ESSNTL-4817: access to all systems when resourceDefinitions=[]

- tasks/caches/refresh_packages_caches.go
- tasks/cleaning/clean_unused_data.go
> Poc system_package2 in jobs

- deploy/clowdapp.yaml
- evaluator/evaluate.go
> SPM-2112: disable baseline for satellite migrated system

- base/api/client.go
- base/vmaas/vmaas.go
- evaluator/evaluate_test.go
- platform/vmaas.go
> RHINENG-1602: fix pod restart when vmaas responds with 400

- docs/v3/openapi.json
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/advisory_systems_v3.go
- manager/controllers/common_attributes.go
- manager/controllers/systems.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
> SPM-2104: show satellite_managed in API

- docs/v3/openapi.json
- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/advisory_systems_test.go
- manager/controllers/advisory_systems_v3.go
- manager/controllers/common_attributes.go
- manager/controllers/systems.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_test.go
> SPM-2106: show in API whether satellite system was uploaded with cache

- base/database/testing.go
- base/models/models.go
- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- dev/test_data.sql
- docs/md/database.md
- evaluator/evaluate.go
- evaluator/evaluate_packages.go
- evaluator/evaluate_test.go
- evaluator/package_cache_test.go
- manager/controllers/package_detail_test.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/package_systems_test.go
- tasks/caches/refresh_packages_caches_test.go
- tasks/cleaning/clean_unused_data.go
- tasks/cleaning/clean_unused_data_test.go
- tasks/vmaas_sync/metrics_test.go
> POC: evaluator with system_package2

- manager/controllers/advisories_test.go
> RHINENG-1638: fix flaky unit tests

- base/database/query.go
- docs/v3/openapi.json
- manager/controllers/advisories_test.go
- manager/controllers/advisory_systems.go
- manager/controllers/baseline_systems.go
- manager/controllers/common_attributes.go
- manager/controllers/filter_test.go
- manager/controllers/system_advisories_test.go
- manager/controllers/systems.go
> RHINENG-1835: sort hosts by inventory group name

- manager/controllers/common_attributes.go
> RHINENG-1835: sort groups by name

- base/database/utils.go
> RHINENG-2309: fix where conditions with inventory groups

- evaluator/evaluate.go
> Add additional data to package analysis log

- base/utils/config.go
> RHINENG-2394: use default CA if CA is not provided by clowder

- docs/v3/openapi.json
- manager/controllers/structures.go
- manager/controllers/systems.go
- manager/controllers/utils.go
> RHINENG-2547: add satellite_managed info to /ids/systems

- base/mqueue/mqueue_impl_gokafka.go
- base/utils/config.go
- deploy/clowdapp.yaml
Revert kafka CA changes since they caused restarts of listener and evaluator in production
> Revert kafka CA changes

- base/mqueue/mqueue_impl_gokafka.go
> add trace logging for kafka headers

- base/utils/config.go
- deploy/clowdapp.yaml
- go.mod
- go.sum
- manager/manager.go
- manager/middlewares/limits.go
- manager/middlewares/request_size.go
> Countermeasures from threat modeling

- docs/v3/openapi.json
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export_test.go
package/package_name/systems
RHINENG-2627
> feat(manager): return satellite_managed flag in

- manager/controllers/advisories_export_test.go
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/baseline_systems_export_test.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/packages_export_test.go
- manager/controllers/system_advisories_export_test.go
- manager/controllers/system_packages_export_test.go
- manager/controllers/systems_export_test.go
- manager/controllers/utils.go
> RHINENG-2843: use crlf in csv

- base/inventory/inventory.go
- base/vmaas/vmaas.go
- docs/v3/openapi.json
- listener/upload.go
- listener/upload_test.go
> RHINENG-2473: parse repository_paths and use in vmaas request

- tasks/vmaas_sync/repo_based.go
> RHINENG-2610: don't panic when latestRepoChange is nil

- deploy/clowdapp.yaml
> POC: fix migration job clowdapp.yaml

- .github/workflows/open_api_spec.yml
> check latest openapi spec

- database_admin/migrations/117_migrate_system_package2.up.sql
- turnpike/controllers/admin.go
- increase batch size to 5000
- log every millionth insert
- truncate system_package2 table when migration fails
- don't fail when removal of constraints fails
> RHINENG-5394: system_package migration improvements

- tasks/vmaas_sync/repo_based.go
- last page of /repos response does not necessarily has the latest `latest_repo_change` timestamp
- add 1s to timestamp due to truncation of milliseconds in a format we use in DB 
> RHINENG-6802: fix repo based reevalution timestamp

- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/evaluate_test.go
- evaluator/package_cache_test.go
> RHINENG-6806: port evaluator improvements from POC2 into master

- tasks/vmaas_sync/repo_based.go
> RHINENG-6802: skip re-calc when latest_repo_change is nil

- database_admin/migrations/123_yum_updates_unchanged_trigger.up.sql
- database_admin/schema/create_schema.sql
> RHINENG-7796: check yum_updates in unchanged trigger

- base/utils/rpm.go
- base/utils/vmaas.go
- base/utils/vmaas_test.go
- evaluator/evaluate.go
- evaluator/evaluate_packages.go
- listener/upload.go
> RHINENG-7752: skip malformed package nevra

- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/packages.go
> RHINENG-7849: don't use cache for ungrouped inventory group

- base/database/testing.go
- evaluator/evaluate_packages.go
- evaluator/evaluate_packages_test.go
- evaluator/evaluate_test.go
- evaluator/package_cache_test.go
> RHINENG-8202: delete old packages by package_id not name_id

- manager/controllers/baseline_detail.go
- manager/controllers/baselines.go
- manager/controllers/utils.go
> RHINENG-8132: remove v1 and v2 compatibility from /baselines

- docs/v3/openapi.json
- manager/controllers/package_systems.go
- manager/controllers/package_systems_export.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/packages.go
- manager/controllers/packages_export.go
- manager/controllers/system_packages.go
- manager/controllers/system_packages_export.go
- manager/controllers/system_packages_export_test.go
- manager/controllers/system_packages_test.go
> RHINENG-8131: remove v1 and v2 compatibility from /packages

- base/mqueue/mqueue_impl_gokafka.go
- base/utils/config.go
- conf/cdappconfig.json
> RHINENG-8407: use system cert pool by default

- docs/v3/openapi.json
- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/advisories_export_test.go
- manager/controllers/advisories_test.go
- manager/controllers/advisory_detail.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/system_advisories.go
- manager/controllers/system_advisories_export_test.go
> RHINENG-8130: remove v1 and v2 compatibility from /advisories

- manager/controllers/systems_advisories_view.go
> RHINENG-8134: remove v1 and v2 compatibility from /views

- deploy/clowdapp.yaml
> RHINENG-8138: make floorist chunksize configurable

- Dockerfile
- dev/database/Dockerfile
> RHINENG-3168: upgrade test env postresql to 16.1

- base/database/testing.go
- manager/controllers/baseline_create.go
- manager/controllers/baseline_create_test.go
- manager/controllers/baseline_update.go
- manager/controllers/baseline_update_test.go
> RHINENG-8664: check inventory groups in baselines

- base/core/gintesting.go
- dashboards/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
- dev/scripts/advisories_list.sh
- dev/scripts/advisory_detail.sh
- dev/scripts/advisory_systems.sh
- dev/scripts/system_detail.sh
- dev/scripts/system_packages.sh
- dev/scripts/systems_applicable.sh
- dev/scripts/systems_list.sh
- manager/controllers/advisories.go
- manager/controllers/advisories_export.go
- manager/controllers/advisory_detail_test.go
- manager/controllers/baselines.go
- manager/controllers/packages.go
- manager/controllers/packages_export.go
- manager/controllers/utils.go
- scripts/go_test_on_ci.sh
> RHINENG-8708: update everything related to API version change

- manager/controllers/advisory_systems.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/baseline_systems.go
- manager/controllers/baseline_systems_export.go
- manager/controllers/common_attributes.go
- manager/controllers/package_systems.go
- manager/controllers/system_detail.go
- manager/controllers/systems.go
- manager/controllers/systems_export.go
- manager/controllers/utils.go
defined Value()/Scan() on jsonb columns so they are parsed directly by gorm
> RHINENG-8707: simplified tags and groups handling

- base/mqueue/template_event.go
- base/utils/config.go
- conf/cdappconfig.json
- conf/common.env
- conf/local.env
- conf/platform.env
- deploy/clowdapp.yaml
- dev/kafka/setup.sh
- go.mod
- platform/platform.go
I wanted to use the struct by importing content-sources but it installed many dependencies and updated some others we are currently using. There was a problem with 1 openapi dependency which is incompatible with our current code. We could import structs from content-sources after we update our dependencies.
> RHINENG-8487: platform mock for testing templates

- docs/v3/openapi.json
- manager/controllers/packages_export.go
> RHINENG-8751: fix /export/packages filter description

- deploy/clowdapp.yaml
> use postgresql 16 in epehemeral

- base/utils/http.go
The SIGSEGV originates in function `HTTPCallRetry` at line 40 (file *base/utils/http.go*):
```go
resp.Body.Close()
```
The `resp` comes from `httpCallFun` that is passed into the function as a parameter:
```go
func HTTPCallRetry(ctx context.Context, httpCallFun func() (outputDataPtr interface{},
resp *http.Response, err error), exponentialRetry bool, maxRetries int, codesToRetry ...int) (
outputDataPtr interface{}, err error) { ... }
```
```go
outDataPtr, resp, callErr := httpCallFun()
```
`HTTPCallRetry` function is called in `callVMaas` (file *evaluator/evaluate.go*) and `vmaasCallFunc` is passed in as `httpCallFun`.
```go
vmaasDataPtr, err := utils.HTTPCallRetry(base.Context, vmaasCallFunc, vmaasCallUseExpRetry,
vmaasCallMaxRetries, http.StatusServiceUnavailable)
```
```go …
```
> RHINENG-7099: fix evaluator-recalc nil pointer dereference

- manager/controllers/structures.go
> RHINENG-8389: fix json response key case

- docker-compose.prod.yml
- docker-compose.yml
> modify docker compose yml for podman-compose

- deploy/clowdapp.yaml
> RHINENG-8919: set floorist job resources

- deploy/clowdapp.yaml
- manager/manager.go
- manager/routes/routes.go
> RHINENG-7684: allow template API enablement from env

- Dockerfile
> RHINENG-9202: remove root group

- evaluator/evaluate_packages.go
- listener/common_test.go
- listener/events_test.go
- listener/metrics.go
- listener/upload.go
Storing system packages: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
> RHINENG-9238: check duplicate packageID before insert

- base/models/models.go
- base/mqueue/payload_tracker_event.go
- deploy/clowdapp.yaml
- dev/scripts/kafka-send-message.sh
- docker-compose.prod.yml
- docker-compose.yml
- listener/events.go
- listener/listener.go
- listener/metrics.go
- listener/template_test.go
- listener/templates.go
- listener/upload.go
> RHINENG-8045: synchronize templates from content-sources

- database_admin/migrate.go
> RHINENG-9461: error comparison in migration

- README.md
- dev/grafana/Dockerfile
> fix grafana dashboard path

- build_deploy.sh
> don't repush original image when building in security-compliance branch

- base/mqueue/template_event.go
- listener/template_test.go
- listener/templates.go
- platform/platform.go
> RHINENG-9702: store null when description is empty

- go.mod
- go.sum
- manager/middlewares/rbac.go
- manager/middlewares/rbac_test.go
> RHINENG-9704: simplify RBAC check

- base/database/testing.go
- base/database/utils_test.go
- base/vmaas/vmaas.go
- dev/test_data.sql
- go.sum
- listener/common_test.go
- manager/controllers/systems_auth_test.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_ids_test.go
- manager/controllers/systems_test.go
- platform/vmaas.go
- tasks/system_culling/system_culling_test.go
- tasks/vmaas_sync/metrics_test.go
- tasks/vmaas_sync/repo_based.go
- tasks/vmaas_sync/repo_based_test.go
- tasks/vmaas_sync/repo_sync.go
> RHINENG-9778: recalc systems with changed packages in repos

- deploy/clowdapp.yaml
- listener/listener.go
> RHINENG-10027: pass template feature flag to listener

- manager/controllers/template_systems.go
- manager/controllers/template_systems_test.go
- manager/controllers/template_systems_update.go
> RHINENG-10030: handle uuid errors

- base/core/config.go
- conf/listener.env
- conf/test.env
- deploy/clowdapp.yaml
- listener/listener.go
> RHINENG-9873: move defaults from clowdapp.yaml into code

- tasks/vmaas_sync/repo_based.go
first select systems based on changed repos (inner select) and then filter them based on changed packages
> RHINENG-10403: tune repo-package query

- tasks/config.go
- tasks/vmaas_sync/repo_based.go
set maximum of repoPackages pairs to fix max_stack db error
> RHINENG-10403: limit when to run repo based recalc

- manager/controllers/baseline_delete.go
> RHINENG-10521: get list of systems _before_ we remove them

- listener/upload.go
> RHINENG-10440: use repository paths of enabled repos

- deploy/clowdapp.yaml
> RHINENG-10941: setup candlepin env

- manager/controllers/package_detail.go
> RHINENG-10927: fix package api if package_name can be parsed as nevra

- deploy/clowdapp.yaml
> RHINENG-10941: dummy candlepin secret for ephemeral env

- docs/v3/openapi.json
- manager/controllers/advisories_export.go
- manager/controllers/advisory_systems_export.go
- manager/controllers/baseline_systems_export.go
- manager/controllers/package_systems_export.go
- manager/controllers/packages_export.go
- manager/controllers/system_advisories_export.go
- manager/controllers/system_packages_export.go
- manager/controllers/systems_export.go
- manager/controllers/template_systems_export.go
Add information to API description that export endpoints are not paginated even if it should be already visible by not having limit and offset parameters for /export endpoints
> RHINENG-10978: document that /export is not paginated

- docs/v3/openapi.json
- manager/controllers/common_attributes.go
- manager/controllers/systems.go
- manager/controllers/systems_export.go
- manager/controllers/systems_export_test.go
- manager/controllers/systems_ids_test.go
- manager/controllers/systems_test.go
> RHINENG-11299: arch attribute and filter for /systems

- pr_check.sh
> don't remove resources from content-sources

- .github/workflows/open_api_spec.yml
- .github/workflows/semantic-release.yml
- .github/workflows/unittests.yml
> RHINENG-11310: update github actions

- docs/v3/openapi.json
- manager/controllers/advisory_systems_export_test.go
- manager/controllers/common_attributes.go
- manager/controllers/package_systems_export_test.go
- manager/controllers/systems_export_test.go
> RHINENG-11303: show template uuid in /systems response

- .github/workflows/unittests.yml
https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/
> docker-compose is no longer supported

- deploy/clowdapp.yaml
> RHINENG-11870: content-sources is optional dependency

- manager/middlewares/rbac.go
> RHINENG-11685: add debug logs

- dashboards/app-sre/grafana-dashboard-insights-patchman-engine-general.configmap.yaml
> fix(grafana): new rds data metric sources

- deploy/clowdapp.yaml
> RHINENG-9505: expose CA cert in deployment

- database_admin/migrations/130_recreate_pg_repack_extension.up.sql
- database_admin/schema/create_schema.sql
> RHINENG-10032: recreate pg_repack extension

- base/mqueue/mqueue_impl_gokafka.go
- database_admin/migrate.go
- dev/grafana/Dockerfile
- dev/grafana/extract_dashboard.py
- manager/controllers/utils.go
> RHINENG-12951: fix snyk findings

- .snyk
> RHINENG-12951: ignore unused test only dependencies

- renovate.json
> Automerge PRs updating konflux references

- .tekton/patchman-engine-push.yaml
> build only tagged images in Konflux

- .github/workflows/semantic-release.yml
- deploy/clowdapp.yaml
> stop using different image_tags for every pod

- .github/workflows/semantic-release.yml
> Use vmaas-bot user to push tag to master branch

- deploy/clowdapp.yaml
set default values according to prod environment
> RHINENG-11562: rename resources env vars

- Dockerfile
> RHINENG-13892, RHINENG-13911: revert to ubi8

- deploy/clowdapp.yaml
minReplicas is deprecated https://redhatinsights.github.io/clowder/clowder/dev/api_reference.html\#k8s-api-github-com-redhatinsights-clowder-apis-cloud-redhat-com-v1alpha1-deployment
> chore: use replicas instead of minReplicas

- evaluator/evaluate_advisories.go
fix deadlocks when inserting to db in when processing multiple systems
> RHINENG-11955: sort advisory_account_data before insert

- deploy/clowdapp.yaml
> RHINENG-15327: add templates metrics to floorist

- .tekton/patchman-engine-pull-request.yaml
- .tekton/patchman-engine-push.yaml
> RHINENG-15504: fix konflux buildah task

- go.mod
> RHINENG-15502: update go version/deps to fix snyk findings

- deploy/clowdapp.yaml
> RHINENG-15327: add last_upload to floorist system report

- deploy/clowdapp.yaml
> RHINENG-15327: overcome uuid issue in floorist

- deploy/clowdapp.yaml
> RHINENG-15327: deafult chunk size creates huge number of small files

- Dockerfile
- dev/sonar/Dockerfile
> RHINENG-15672: move to ubi9 images

- base/inventory/inventory.go
- listener/common_test.go
- listener/upload.go
- listener/upload_test.go
> RHINENG-14953: use per_reporter_staleness value for last_upload

- base/candlepin/candlepin.go
- base/utils/gin.go
- manager/controllers/template_subscribed_systems_update.go
- manager/controllers/template_subscribed_systems_update_test.go
- manager/controllers/template_systems_delete.go
- manager/controllers/template_systems_update.go
- manager/middlewares/authentication.go
- platform/candlepin.go
> RHINENG-15506: use candlepin bulk API

- evaluator/evaluate.go
- evaluator/evaluate_advisories.go
> RHINENG-11956: skip insert if system has been deleted

- base/candlepin/candlepin.go
- base/utils/gin.go
- manager/controllers/template_subscribed_systems_update.go
- manager/controllers/template_subscribed_systems_update_test.go
- manager/controllers/template_systems_delete.go
- manager/controllers/template_systems_update.go
- manager/middlewares/authentication.go
- platform/candlepin.go
> RHINENG-15506: revert changes until we can test it 

- tasks/vmaas_sync/advisory_sync.go
> RHINENG-16011: parse timestamp with Z in advisory sync

- evaluator/remediations.go
> RHINENG-16080: don't rewrite errata installablity for single system

- evaluator/evaluate.go
so other sessions won't delete it before insert
> RHINENG-11956: lock the system

- base/database/batch.go
- base/database/batch_test.go
- base/types/timestamp.go
- listener/upload.go
> RHINENG-16288: don't use RETURNING where it is not necessary

- base/mqueue/event.go
- base/mqueue/mqueue.go
- base/utils/http.go
- base/utils/http_test.go
- evaluator/evaluate.go
- go.mod
- go.sum
- manager/controllers/template_systems_update.go
- tasks/vmaas_sync/advisory_sync.go
- tasks/vmaas_sync/dbchange.go
- tasks/vmaas_sync/package_sync.go
- tasks/vmaas_sync/repo_based.go
> RHINENG-16331: update backoff to v2

- base/mqueue/mqueue.go
> RHINENG-16331: fix context cancel in kafka handler

- renovate.json
> RHINENG-16324: disable upgrade of go toolchain

- docs/admin/openapi.json
- manager/routes/routes.go
- turnpike/controllers/admin.go
- turnpike/controllers/database.go
- turnpike/controllers/pprof.go
- internal api to re-create pg_repack extension
- internal api refactoring
> RHINENG-16449: internal api to re-create pg_repack extension

- pr_check.sh
tests keep failing in every PR, disable tests, keep only PR build and deploy to ephemeral
@niyazRedhat FYI
> Disable PR check tests

- evaluator/evaluate_packages.go
- evaluator/package_cache.go
- evaluator/package_cache_test.go
bulk load packages missing in cache but present in DB
> RHINENG-16781: refactor getMissingPackages

- tasks/repack/repack.go
rather do nothing than kill transactions
> fix(repack): give 600s timeout to acquire exclusive lock and skip repack if not succeeded

- pr_check.sh
> Re-enable pr check runs

- base/database/testing.go
- base/inventory/inventory.go
- listener/rhsm.go
- listener/rhsm_test.go
- listener/upload.go
- manager/controllers/baseline_create_test.go
- manager/controllers/baseline_update_test.go
> RHINENG-14719: set system template based on rhsm environments

- renovate.json
> chore(renovate): remove packageRules which don't work

- .tekton/patchman-engine-pull-request.yaml
- .tekton/patchman-engine-push.yaml
> Update tekton pipelines - add tasks - SAST Unicode and Shell Check tasks/SAST Coverity Check tasks

- base/deprecations/deprecations.go
- docs/v3/openapi.json
- evaluator/evaluate.go
- manager/controllers/baseline_create.go
- manager/controllers/baseline_delete.go
- manager/controllers/baseline_detail.go
- manager/controllers/baseline_systems.go
- manager/controllers/baseline_systems_remove.go
- manager/controllers/baseline_update.go
- manager/controllers/baselines.go
- manager/routes/routes.go
> RHINENG-15782: deprecate baselines

- listener/listener.go
- listener/rhsm.go
- listener/upload.go
> HMS-5960: don't remove templates in listener

- base/candlepin/candlepin.go
- base/inventory/inventory.go
- listener/rhsm.go
- listener/upload.go
- listener/upload_test.go
- manager/config/config.go
- manager/controllers/template_systems_update.go
- manager/middlewares/rbac.go
- platform/candlepin.go
> RHINENG-17345: assign template according to system's environment in candlepin

- deploy/clowdapp.yaml
> RHINENG-17345: setup candlepin env for listener

- renovate.json
> fix: setup mintmaker/renovate to autocommit PRs

- manager/middlewares/rbac.go
- manager/middlewares/rbac_test.go
> RHINENG-18385: allow 'equal' opration in resourceDefinitions
